// DO NOT MODIFY. Auto-generated by vitest.setup.ts from FROGBOT_DATABASE env var.

  import { sqliteAdapter } from '@frogbot/db-sqlite'

  export const databaseAdapter = sqliteAdapter({
    client: {
      url: process.env.SQLITE_URL || process.env.DATABASE_URL || 'file:./test-payload.db',
    },
  })
