/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tasks: Task;
    articles: Article;
    issues: Issue;
    reports: Report;
    'usage-logs': UsageLog;
    'frogbot-waitpoints': FrogBotWaitpoint;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    tasks: TasksSelect;
    articles: ArticlesSelect;
    issues: IssuesSelect;
    reports: ReportsSelect;
    'usage-logs': UsageLogsSelect;
    'frogbot-waitpoints': FrogBotWaitpointsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'fr')
    | ('en' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'frogbot-reset-ai-budgets': TaskFrogBotResetAiBudgets;
      'frogbot-sweep-jobs': TaskFrogBotSweepJobs;
      'frogbot-cleanup-kv': TaskFrogBotCleanupKv;
      'frogbot-run-ai-field': TaskFrogBotRunAIField;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'editor' | 'author' | 'viewer' | 'blind') | null;
  modelAccess?: ('all' | 'selected') | null;
  models?: ('test/other-model' | 'test/writer-model')[] | null;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  monthlyBudget?: number | null;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  spendThisPeriodUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title?: string | null;
  notes?: string | null;
  priority?: number | null;
  secret?: string | null;
  /**
   * Generated automatically by AI from: title, notes, secret. Writing a value keeps it and stops automatic updates
   */
  summary?: string | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _summary_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _summary_error?: string | null;
  /**
   * Generated automatically by AI from: summary. Writing a value keeps it and stops automatic updates
   */
  category?: string | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _category_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _category_error?: string | null;
  /**
   * Set by FrogBot to the user who last saved the record; read-only
   */
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  body?: string | null;
  /**
   * Generated automatically by AI from: body. Writing a value keeps it and stops automatic updates
   */
  summary?: string | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _summary_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _summary_error?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  notes?: string | null;
  /**
   * Generated automatically by AI from: notes. Writing a value keeps it and stops automatic updates
   */
  type?: ('bug' | 'feature' | 'question') | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _type_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _type_error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  body?: string | null;
  /**
   * Generated automatically by AI from: body. Writing a value keeps it and stops automatic updates
   */
  labels?: ('ui' | 'api' | 'docs')[] | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _labels_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _labels_error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs".
 */
export interface UsageLog {
  id: number;
  user?: (number | null) | User;
  requestId: string;
  runId?: string | null;
  model: string;
  operation:
    | 'chat.completions'
    | 'messages'
    | 'responses'
    | 'embeddings'
    | 'images'
    | 'speech'
    | 'transcriptions'
    | 'videos'
    | 'rerank'
    | 'evaluate';
  inputTokens: number;
  outputTokens: number;
  cachedInputTokens?: number | null;
  cacheWriteTokens?: number | null;
  reasoningTokens?: number | null;
  totalTokens: number;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  costUSD: number;
  finishReason?: string | null;
  requestedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints".
 */
export interface FrogBotWaitpoint {
  id: number;
  jobId: string;
  holder?: (number | null) | null;
  name: string;
  token: string;
  kind: 'delay' | 'resumable';
  ready: boolean;
  status: 'pending' | 'resumed' | 'expired';
  expiresAt?: string | null;
  until?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dispatched: boolean;
  dispatchOwner?: string | null;
  dispatchLeaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  role?: boolean;
  modelAccess?: boolean;
  models?: boolean;
  monthlyBudget?: boolean;
  spendThisPeriodUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  resetPasswordRequestedAt?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect {
  title?: boolean;
  notes?: boolean;
  priority?: boolean;
  secret?: boolean;
  summary?: boolean;
  _summary_status?: boolean;
  _summary_error?: boolean;
  category?: boolean;
  _category_status?: boolean;
  _category_error?: boolean;
  lastModifiedBy?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect {
  body?: boolean;
  summary?: boolean;
  _summary_status?: boolean;
  _summary_error?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect {
  notes?: boolean;
  type?: boolean;
  _type_status?: boolean;
  _type_error?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect {
  body?: boolean;
  labels?: boolean;
  _labels_status?: boolean;
  _labels_error?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs_select".
 */
export interface UsageLogsSelect {
  user?: boolean;
  requestId?: boolean;
  runId?: boolean;
  model?: boolean;
  operation?: boolean;
  inputTokens?: boolean;
  outputTokens?: boolean;
  cachedInputTokens?: boolean;
  cacheWriteTokens?: boolean;
  reasoningTokens?: boolean;
  totalTokens?: boolean;
  costUSD?: boolean;
  finishReason?: boolean;
  requestedAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints_select".
 */
export interface FrogBotWaitpointsSelect {
  jobId?: boolean;
  holder?: boolean;
  name?: boolean;
  token?: boolean;
  kind?: boolean;
  ready?: boolean;
  status?: boolean;
  expiresAt?: boolean;
  until?: boolean;
  data?: boolean;
  dispatched?: boolean;
  dispatchOwner?: boolean;
  dispatchLeaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotResetAiBudgets".
 */
export interface TaskFrogBotResetAiBudgets {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotSweepJobs".
 */
export interface TaskFrogBotSweepJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotCleanupKv".
 */
export interface TaskFrogBotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotRunAIField".
 */
export interface TaskFrogBotRunAIField {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {};
    models: 'test/other-model' | 'test/writer-model';
    roles: never;
  }
}
