packages:
  - 'packages/*'
  - 'packages/pieces/*'
  - 'packages/plugins/*'
  - 'test'
  - 'templates/blank'
  - 'test/e2e/fixtures/tool-agent'
  - 'test/e2e/fixtures/rich-text'
  - 'examples/business-qa'
  - 'examples/tailwind'
