/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    tickets: Ticket;
    'api-keys': ApiKey;
    'frogbot-waitpoints': FrogBotWaitpoint;
    'frogbot-autonumbers': FrogBotAutonumber;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    posts: PostsSelect;
    tickets: TicketsSelect;
    'api-keys': ApiKeysSelect;
    'frogbot-waitpoints': FrogBotWaitpointsSelect;
    'frogbot-autonumbers': FrogBotAutonumbersSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | null;
  jobs: {
    tasks: {
      'frogbot-sweep-jobs': TaskFrogBotSweepJobs;
      'frogbot-cleanup-kv': TaskFrogBotCleanupKv;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  /**
   * Retail price (decimal amount in USD, in whole units, not minor units such as cents)
   */
  price?: number | null;
  cost?: {
    /**
     * Decimal amount in EUR, in whole units, not minor units such as cents
     */
    wholesale?: number | null;
  };
  /**
   * Whole-number rating from 1 to 5
   */
  score?: number | null;
  /**
   * Duration in whole seconds, for example 5400 for 1 hour 30 minutes
   */
  timeSpent?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  title?: string | null;
  /**
   * Unique number set by FrogBot when the record is created; read-only
   */
  number?: number | null;
  /**
   * Set by FrogBot to the user who created the record; read-only
   */
  createdBy?: (number | null) | User;
  /**
   * Set by FrogBot to the user who last saved the record; read-only
   */
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  name: string;
  owner: number | User;
  prefix: string;
  tokenHash: string;
  lastUsedAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints".
 */
export interface FrogBotWaitpoint {
  id: number;
  jobId: string;
  holder?: (number | null) | null;
  name: string;
  token: string;
  kind: 'delay' | 'resumable';
  ready: boolean;
  status: 'pending' | 'resumed' | 'expired';
  expiresAt?: string | null;
  until?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dispatched: boolean;
  dispatchOwner?: string | null;
  dispatchLeaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-autonumbers".
 */
export interface FrogBotAutonumber {
  id: number;
  key: string;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  resetPasswordRequestedAt?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect {
  title?: boolean;
  price?: boolean;
  cost?:
    | boolean
    | {
        wholesale?: boolean;
      };
  score?: boolean;
  timeSpent?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect {
  title?: boolean;
  number?: boolean;
  createdBy?: boolean;
  lastModifiedBy?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect {
  name?: boolean;
  owner?: boolean;
  prefix?: boolean;
  tokenHash?: boolean;
  lastUsedAt?: boolean;
  revokedAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints_select".
 */
export interface FrogBotWaitpointsSelect {
  jobId?: boolean;
  holder?: boolean;
  name?: boolean;
  token?: boolean;
  kind?: boolean;
  ready?: boolean;
  status?: boolean;
  expiresAt?: boolean;
  until?: boolean;
  data?: boolean;
  dispatched?: boolean;
  dispatchOwner?: boolean;
  dispatchLeaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-autonumbers_select".
 */
export interface FrogBotAutonumbersSelect {
  key?: boolean;
  value?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotSweepJobs".
 */
export interface TaskFrogBotSweepJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotCleanupKv".
 */
export interface TaskFrogBotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {};
    models: never;
    roles: never;
  }
}
