import fs from 'node:fs/promises';
import { isAbsolute, join, resolve } from 'node:path';

import type { AcceptedLanguages } from '@payloadcms/translations';
import { initI18n } from '@payloadcms/translations';
import { compile } from 'json-schema-to-typescript';
import type { SanitizedConfig } from 'payload';
import { configToJSONSchema } from 'payload';
import { format } from 'prettier';

import { getConfiguredModelIds } from '../ai/models.js';
import type { SanitizedAIConfig } from '../ai/types.js';
import type { FrogBotSanitizedConfig } from '../config/sanitized.js';

const BANNER = `/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run \`frogbot generate:types\` to regenerate this file.
 */`;

export function buildGeneratedTypesFooter(
  agentSlugs: readonly string[],
  ai?: SanitizedAIConfig,
  roleSlugs: readonly string[] = [],
): string {
  const agents =
    agentSlugs.length === 0
      ? '{}'
      : `{
${agentSlugs.map((slug) => `      ${JSON.stringify(slug)}: unknown;`).join('\n')}
    }`;

  const modelIds = getConfiguredModelIds(ai);
  const models =
    modelIds.length === 0 ? 'never' : modelIds.map((id) => JSON.stringify(id)).join(' | ');

  const roles =
    roleSlugs.length === 0 ? 'never' : roleSlugs.map((slug) => JSON.stringify(slug)).join(' | ');

  return `declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: ${agents};
    models: ${models};
    roles: ${roles};
  }
}`;
}

const DEFAULT_FILENAME = 'frogbot-types.ts';

type SchemaGroup = {
  properties?: Record<string, unknown>;
  required?: string[];
  [key: string]: unknown;
};

type ConfigJSONSchema = {
  properties?: Record<string, SchemaGroup | undefined>;
  definitions?: Record<string, unknown>;
};

function stripRefs(schema: unknown, stripped: ReadonlySet<string>): void {
  if (!schema || typeof schema !== 'object') return;
  if (Array.isArray(schema)) {
    for (const item of schema) stripRefs(item, stripped);

    return;
  }

  const obj = schema as Record<string, unknown>;
  if (typeof obj.$ref === 'string') {
    const match = /#\/definitions\/(.+)/.exec(obj.$ref);
    if (match && stripped.has(match[1])) {
      delete obj.$ref;
      obj.type = 'null';
    }
  }

  for (const value of Object.values(obj)) {
    stripRefs(value, stripped);
  }
}

export function stripInternalCollections(schema: ConfigJSONSchema): void {
  const isInternal = (slug: string) => slug.startsWith('payload-');

  for (const key of [
    'collections',
    'collectionsJoins',
    'collectionsSelect',
    'globals',
    'globalsSelect',
  ]) {
    const group = schema.properties?.[key];
    if (!group) continue;

    for (const slug of Object.keys(group.properties ?? {})) {
      if (isInternal(slug)) delete group.properties![slug];
    }

    if (Array.isArray(group.required)) {
      group.required = group.required.filter((slug) => !isInternal(slug));
    }
  }

  const internalDefs = new Set(Object.keys(schema.definitions ?? {}).filter(isInternal));
  if (internalDefs.size === 0) return;

  for (const name of internalDefs) {
    delete schema.definitions![name];
  }

  stripRefs(schema, internalDefs);
}

const INTERNAL_PREFIX = 'frogbot-';

const INTERNAL_SELECT = /^(frogbot-.+)_select$/;

export function internalSelectName(slug: string): string {
  const words = slug
    .slice(INTERNAL_PREFIX.length)
    .split(/[^a-zA-Z0-9]+/)
    .map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`);

  return `FrogBot${words.join('')}Select`;
}

export function nameInternalSelects(schema: ConfigJSONSchema): void {
  for (const [name, definition] of Object.entries(schema.definitions ?? {})) {
    const slug = INTERNAL_SELECT.exec(name)?.[1];

    if (slug && definition && typeof definition === 'object') {
      (definition as { title?: string }).title = internalSelectName(slug);
    }
  }
}

function resolveOutputPath(config: SanitizedConfig, dir: string): string {
  const fromEnv = process.env.FROGBOT_TS_OUTPUT_PATH;
  if (fromEnv) return isAbsolute(fromEnv) ? fromEnv : resolve(dir, fromEnv);

  const fromConfig = config.typescript?.outputFile;
  if (fromConfig && !fromConfig.endsWith('/payload-types.ts')) return fromConfig;

  return join(resolve(dir), DEFAULT_FILENAME);
}

async function compileTypes(
  config: SanitizedConfig,
  agentSlugs: readonly string[],
  ai?: SanitizedAIConfig,
  roleSlugs: readonly string[] = [],
): Promise<string> {
  const languages = Object.keys(config.i18n.supportedLanguages) as AcceptedLanguages[];
  const language = languages.includes('en') ? 'en' : config.i18n.fallbackLanguage;
  const i18n = await initI18n({
    config: config.i18n,
    context: 'api',
    language,
  });

  const result = configToJSONSchema(config, config.db.defaultIDType, i18n) as
    { jsonSchema: unknown; typeStringDefinitions?: Set<string> } | object;

  const jsonSchema =
    'jsonSchema' in result ? (result as { jsonSchema: unknown }).jsonSchema : result;

  stripInternalCollections(jsonSchema as ConfigJSONSchema);
  nameInternalSelects(jsonSchema as ConfigJSONSchema);
  const extraTypeStrings =
    'typeStringDefinitions' in result
      ? (result as { typeStringDefinitions?: Set<string> }).typeStringDefinitions
      : undefined;

  let compiled = await compile(jsonSchema as Parameters<typeof compile>[0], 'Config', {
    bannerComment: BANNER,
    style: { singleQuote: true },
    unreachableDefinitions: true,
    cwd: process.cwd(),
  });

  if (extraTypeStrings && extraTypeStrings.size > 0) {
    compiled = `${compiled.trimEnd()}\n\n${[...extraTypeStrings].join('\n\n')}\n`;
  }

  const output = `${compiled.trimEnd()}\n\n\n${buildGeneratedTypesFooter(agentSlugs, ai, roleSlugs)}\n`;

  return format(output, { parser: 'typescript', singleQuote: true });
}

export async function writeGeneratedTypes(
  frogbotConfig: FrogBotSanitizedConfig,
  configDir: string,
): Promise<{ outputPath: string; changed: boolean }> {
  const config = await frogbotConfig._internal.payloadConfig;
  const outputPath = resolveOutputPath(config, configDir);
  const compiled = await compileTypes(
    config,
    frogbotConfig.agents?.map((agent) => agent.slug) ?? [],
    frogbotConfig.ai,
    frogbotConfig.roles,
  );

  try {
    const existing = await fs.readFile(outputPath, 'utf-8');
    if (existing === compiled) {
      return { outputPath, changed: false };
    }
  } catch {}

  await fs.writeFile(outputPath, compiled);

  return { outputPath, changed: true };
}
