import { z } from 'zod';

export const slackAuth = z.object({
  botToken: z.string().min(1).meta({ label: 'Bot token', secret: true }),
  userToken: z.string().min(1).optional().meta({ label: 'User token', secret: true }),
  teamId: z.string().min(1).optional().meta({ label: 'Workspace ID' }),
});

export const slackOptions = z.object({
  signingSecret: z.string().min(1).optional().meta({ label: 'Signing secret', secret: true }),
});

export type SlackOptions = z.output<typeof slackOptions>;

export const slackScopes = {
  'app_mentions:read': 'app_mentions:read',
  'assistant:write': 'assistant:write',
  'bookmarks:read': 'bookmarks:read',
  'bookmarks:write': 'bookmarks:write',
  'bots:read': 'bots:read',
  'calls:read': 'calls:read',
  'calls:write': 'calls:write',
  'channels:history': 'channels:history',
  'channels:join': 'channels:join',
  'channels:manage': 'channels:manage',
  'channels:read': 'channels:read',
  'channels:write.invites': 'channels:write.invites',
  'chat:write': 'chat:write',
  'chat:write.customize': 'chat:write.customize',
  'chat:write.public': 'chat:write.public',
  commands: 'commands',
  'conversations.connect:manage': 'conversations.connect:manage',
  'conversations.connect:read': 'conversations.connect:read',
  'conversations.connect:write': 'conversations.connect:write',
  'dnd:read': 'dnd:read',
  'emoji:read': 'emoji:read',
  'files:read': 'files:read',
  'files:write': 'files:write',
  'groups:history': 'groups:history',
  'groups:read': 'groups:read',
  'groups:write': 'groups:write',
  'groups:write.invites': 'groups:write.invites',
  'im:history': 'im:history',
  'im:read': 'im:read',
  'im:write': 'im:write',
  'incoming-webhook': 'incoming-webhook',
  'links.embed:write': 'links.embed:write',
  'links:read': 'links:read',
  'links:write': 'links:write',
  'metadata.message:read': 'metadata.message:read',
  'mpim:history': 'mpim:history',
  'mpim:read': 'mpim:read',
  'mpim:write': 'mpim:write',
  'pins:read': 'pins:read',
  'pins:write': 'pins:write',
  'reactions:read': 'reactions:read',
  'reactions:write': 'reactions:write',
  'reminders:read': 'reminders:read',
  'reminders:write': 'reminders:write',
  'remote_files:read': 'remote_files:read',
  'remote_files:share': 'remote_files:share',
  'remote_files:write': 'remote_files:write',
  'team:read': 'team:read',
  'usergroups:read': 'usergroups:read',
  'usergroups:write': 'usergroups:write',
  'users.profile:read': 'users.profile:read',
  'users:read': 'users:read',
  'users:read.email': 'users:read.email',
  'users:write': 'users:write',
} as const;

export const slackDefaultScopes = [
  'channels:history',
  'channels:join',
  'channels:manage',
  'channels:read',
  'channels:write.invites',
  'chat:write',
  'chat:write.customize',
  'conversations.connect:write',
  'emoji:read',
  'files:read',
  'files:write',
  'groups:history',
  'groups:read',
  'groups:write',
  'groups:write.invites',
  'im:history',
  'im:read',
  'im:write',
  'links:read',
  'links:write',
  'mpim:history',
  'mpim:read',
  'mpim:write',
  'reactions:read',
  'reactions:write',
  'usergroups:read',
  'usergroups:write',
  'users.profile:read',
  'users:read',
  'users:read.email',
] as const;
