import { definePiece } from 'frogbot/pieces';

import {
  addComment,
  addContactHandle,
  addConversationLinks,
  addConversationTags,
  assignConversation,
  createAccount,
  createContact,
  createDraft,
  createDraftReply,
  createLink,
  listAccounts,
  removeContactHandle,
  removeConversationLinks,
  removeConversationTags,
  searchContacts,
  searchConversations,
  sendMessage,
  sendReply,
  updateAccount,
  updateContact,
  updateConversation,
  updateLink,
} from './actions.js';
import { createFrontClient } from './client.js';
import { frontAuth, frontOptions } from './config.js';
import {
  commentCreated,
  conversationStatusChanged,
  conversationTagAdded,
  inboundMessageCreated,
  outboundMessageCreated,
} from './triggers.js';

export const frontActions = [
  'addComment',
  'addContactHandle',
  'addConversationLinks',
  'addConversationTags',
  'assignConversation',
  'createAccount',
  'createContact',
  'createDraft',
  'createDraftReply',
  'createLink',
  'listAccounts',
  'searchContacts',
  'searchConversations',
  'removeContactHandle',
  'removeConversationLinks',
  'removeConversationTags',
  'sendMessage',
  'sendReply',
  'updateAccount',
  'updateContact',
  'updateConversation',
  'updateLink',
] as const;
export const frontTriggers = [
  'commentCreated',
  'inboundMessageCreated',
  'outboundMessageCreated',
  'conversationTagAdded',
  'conversationStatusChanged',
] as const;

export const createFront = definePiece({
  slug: 'front',
  label: 'Front',
  admin: {
    description: 'Manage Front contacts, accounts, conversations, messages, and events',
    group: 'Customer Support',
  },
  auth: frontAuth,
  options: frontOptions,
  client: createFrontClient,
  actions: [
    addComment,
    addContactHandle,
    addConversationLinks,
    addConversationTags,
    assignConversation,
    createAccount,
    createContact,
    createDraft,
    createDraftReply,
    createLink,
    listAccounts,
    searchContacts,
    searchConversations,
    removeContactHandle,
    removeConversationLinks,
    removeConversationTags,
    sendMessage,
    sendReply,
    updateAccount,
    updateContact,
    updateConversation,
    updateLink,
  ],
  triggers: [
    commentCreated,
    inboundMessageCreated,
    outboundMessageCreated,
    conversationTagAdded,
    conversationStatusChanged,
  ],
});
