import { describe, expect, it } from 'vitest';

import { generatedTargets, pieceTypesArgs, summarize } from '../../../scripts/check-generated.mjs';

const BANNER = '/**\n * This file was automatically generated by FrogBot.\n */';

function targets(files: string[], contents: Record<string, string> = {}, projects: string[] = []) {
  const existing = new Set([...files, ...Object.keys(contents)]);

  return generatedTargets({
    files,
    projects: new Set(projects),
    exists: (file: string) => existing.has(file),
    read: (file: string) => contents[file] ?? '',
  });
}

describe('check generated', () => {
  it('maps tracked import maps and piece types to their workspace project', () => {
    const found = targets(
      [
        'templates/blank/src/app/(frogbot)/importMap.js',
        'packages/pieces/piece-resend/src/piece-types.ts',
        'packages/frogbot/src/bin/generateImportMap/index.ts',
      ],
      {},
      ['templates/blank', 'packages/pieces/piece-resend'],
    );

    expect(found).toEqual([
      {
        kind: 'importMap',
        file: 'templates/blank/src/app/(frogbot)/importMap.js',
        cwd: 'templates/blank',
      },
      {
        kind: 'pieceTypes',
        file: 'packages/pieces/piece-resend/src/piece-types.ts',
        cwd: 'packages/pieces/piece-resend',
      },
    ]);
  });

  it('pairs generated types with the config next to them', () => {
    const found = targets(
      ['test/chat/frogbot-types.ts', 'templates/blank/src/frogbot-types.ts'],
      {
        'test/chat/frogbot-types.ts': BANNER,
        'test/chat/config.ts': '',
        'templates/blank/src/frogbot-types.ts': BANNER,
        'templates/blank/src/frogbot.config.ts': '',
      },
      ['test', 'templates/blank'],
    );

    expect(found).toEqual([
      { kind: 'types', file: 'test/chat/frogbot-types.ts', config: 'test/chat/config.ts' },
      {
        kind: 'types',
        file: 'templates/blank/src/frogbot-types.ts',
        config: 'templates/blank/src/frogbot.config.ts',
      },
    ]);
  });

  it('skips hand-written frogbot-types.ts files', () => {
    const found = targets(
      ['test/e2e/fixtures/tool-agent/src/frogbot-types.ts'],
      { 'test/e2e/fixtures/tool-agent/src/frogbot-types.ts': "declare module 'frogbot' {}" },
      ['test/e2e/fixtures/tool-agent'],
    );

    expect(found).toEqual([]);
  });

  it('skips files outside the workspace projects', () => {
    const found = targets(
      ['examples/simple/src/app/(frogbot)/importMap.js', 'examples/simple/src/frogbot-types.ts'],
      { 'examples/simple/src/frogbot-types.ts': BANNER },
      ['templates/blank'],
    );

    expect(found).toEqual([]);
  });

  it('builds the piece-types command from the create* factory in src/index.ts', () => {
    const source =
      "import { definePiece } from 'frogbot';\n\nexport const createResend = definePiece({});\n";

    expect(
      pieceTypesArgs(source, {
        file: 'packages/pieces/piece-resend/src/piece-types.ts',
        cwd: 'packages/pieces/piece-resend',
      }),
    ).toEqual([
      'generate:piece-types',
      'src/index.ts',
      '--export',
      'createResend',
      '--output',
      'src/piece-types.ts',
    ]);
  });

  it('rejects a module without exactly one create* factory', () => {
    const target = { file: 'packages/pieces/x/src/piece-types.ts', cwd: 'packages/pieces/x' };

    expect(pieceTypesArgs('export const resend = {};\n', target)).toBeUndefined();
    expect(
      pieceTypesArgs('export const createA = 1;\nexport function createB() {}\n', target),
    ).toBeUndefined();
  });

  it('prints one OK line when every file is fresh', () => {
    const result = summarize([
      { file: 'b.ts', status: 'fresh' },
      { file: 'a.js', status: 'fresh' },
    ]);

    expect(result).toEqual({ ok: true, lines: ['generated: OK (2 files)'] });
  });

  it('prints a sorted stale line per stale file and fails', () => {
    const result = summarize([
      { file: 'b.ts', status: 'stale' },
      { file: 'c.ts', status: 'fresh' },
      { file: 'a.js', status: 'stale' },
    ]);

    expect(result).toEqual({ ok: false, lines: ['stale: a.js', 'stale: b.ts'] });
  });

  it('fails on a generation error', () => {
    const result = summarize([{ file: 'a.ts', status: 'error', message: 'no default export' }]);

    expect(result).toEqual({ ok: false, lines: ['error: a.ts: no default export'] });
  });

  it('lists written files and passes after --write', () => {
    const result = summarize([
      { file: 'a.ts', status: 'written' },
      { file: 'b.ts', status: 'fresh' },
    ]);

    expect(result).toEqual({ ok: true, lines: ['wrote: a.ts', 'generated: OK (2 files)'] });
  });
});
