import { googleOAuth } from '@frogbotai/piece-google';
import { definePiece } from 'frogbot/pieces';

import { customApiCall, exportWorksheet } from './api.js';
import { createGoogleSheetsClient } from './client.js';
import { googleSheetsAuth, googleSheetsScopes } from './config.js';
import {
  appendRow,
  appendRows,
  deleteRow,
  deleteRows,
  findOrCreateRow,
  findRows,
  getNextRows,
  getRow,
  getRows,
  insertRow,
  updateRow,
  updateRows,
} from './rows.js';
import {
  clearRows,
  clearWorksheet,
  copyWorksheet,
  createColumn,
  createSpreadsheet,
  createWorksheet,
  deleteWorksheet,
  findOrCreateWorksheet,
  findSpreadsheets,
  findWorksheets,
  formatRows,
  readRange,
  renameWorksheet,
} from './worksheets.js';

export { googleSheetsScopes };
export const googleSheetsActions = [
  'appendRow',
  'insertRow',
  'appendRows',
  'updateRow',
  'updateRows',
  'deleteRow',
  'deleteRows',
  'findRows',
  'findOrCreateRow',
  'createSpreadsheet',
  'createWorksheet',
  'findOrCreateWorksheet',
  'clearWorksheet',
  'clearRows',
  'deleteWorksheet',
  'renameWorksheet',
  'formatRows',
  'getRow',
  'getNextRows',
  'getRows',
  'readRange',
  'findSpreadsheets',
  'findWorksheets',
  'copyWorksheet',
  'createColumn',
  'exportWorksheet',
  'customApiCall',
] as const;

export const createGoogleSheets = definePiece({
  slug: 'google-sheets',
  label: 'Google Sheets',
  admin: {
    description: 'Read, edit, and manage spreadsheets and worksheets',
    group: 'Productivity',
  },
  auth: googleSheetsAuth,
  client: createGoogleSheetsClient,
  oauth: {
    ...googleOAuth,
    scopes: [...googleOAuth.scopes, ...googleSheetsScopes],
    toAuth: ({ tokens }) => ({
      accessToken: tokens.access_token ?? '',
      refreshToken: tokens.refresh_token,
    }),
  },
  actions: [
    appendRow,
    insertRow,
    appendRows,
    updateRow,
    updateRows,
    deleteRow,
    deleteRows,
    findRows,
    findOrCreateRow,
    createSpreadsheet,
    createWorksheet,
    findOrCreateWorksheet,
    clearWorksheet,
    clearRows,
    deleteWorksheet,
    renameWorksheet,
    formatRows,
    getRow,
    getNextRows,
    getRows,
    readRange,
    findSpreadsheets,
    findWorksheets,
    copyWorksheet,
    createColumn,
    exportWorksheet,
    customApiCall,
  ],
});
