/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    releases: Release;
    'api-keys': ApiKey;
    'usage-logs': UsageLog;
    chats: Chat;
    messages: Message;
    connections: Connection;
    'frogbot-trigger-subscriptions': FrogbotTriggerSubscription;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    media: MediaSelect;
    releases: ReleasesSelect;
    'api-keys': ApiKeysSelect;
    'usage-logs': UsageLogsSelect;
    chats: ChatsSelect;
    messages: MessagesSelect;
    connections: ConnectionsSelect;
    'frogbot-trigger-subscriptions': FrogbotTriggerSubscriptionsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'frogbot-reset-ai-budgets': TaskFrogbotResetAiBudgets;
      'frogbot-cleanup-kv': TaskFrogbotCleanupKv;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  modelAccess?: ('all' | 'selected') | null;
  models?:
    | (
        | 'openai/chatgpt-image-latest'
        | 'openai/gpt-4.1'
        | 'openai/gpt-4.1-mini'
        | 'openai/gpt-4o'
        | 'openai/gpt-4o-2024-08-06'
        | 'openai/gpt-4o-2024-11-20'
        | 'openai/gpt-4o-mini'
        | 'openai/gpt-5'
        | 'openai/gpt-5-mini'
        | 'openai/gpt-5-nano'
        | 'openai/gpt-5-pro'
        | 'openai/gpt-5.1'
        | 'openai/gpt-5.2'
        | 'openai/gpt-5.2-chat-latest'
        | 'openai/gpt-5.2-pro'
        | 'openai/gpt-5.3-chat-latest'
        | 'openai/gpt-5.3-codex'
        | 'openai/gpt-5.3-codex-spark'
        | 'openai/gpt-5.4'
        | 'openai/gpt-5.4-mini'
        | 'openai/gpt-5.4-nano'
        | 'openai/gpt-5.4-pro'
        | 'openai/gpt-5.5'
        | 'openai/gpt-5.5-pro'
        | 'openai/gpt-5.6'
        | 'openai/gpt-5.6-luna'
        | 'openai/gpt-5.6-sol'
        | 'openai/gpt-5.6-terra'
        | 'openai/gpt-image-1-mini'
        | 'openai/gpt-image-1.5'
        | 'openai/gpt-image-2'
        | 'openai/gpt-realtime-2.1'
        | 'openai/o3'
        | 'openai/o3-pro'
        | 'openai/text-embedding-3-large'
        | 'openai/text-embedding-3-small'
        | 'openai/text-embedding-ada-002'
      )[]
    | null;
  monthlyBudget?: number | null;
  spendThisPeriodUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  folder?: (number | null) | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  name: string;
  version: string;
  status: 'planning' | 'qa' | 'ready' | 'released' | 'blocked';
  targetDate: string;
  owner: number | User;
  summary: string;
  acceptanceCriteria?: string | null;
  releaseNotes?: string | null;
  artifacts?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  name: string;
  owner: number | User;
  prefix: string;
  tokenHash: string;
  lastUsedAt?: string | null;
  revokedAt?: string | null;
  totalCostUSD?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs".
 */
export interface UsageLog {
  id: number;
  apiKey?: (number | null) | ApiKey;
  user?: (number | null) | User;
  chat?: (number | null) | Chat;
  requestId: string;
  runId?: string | null;
  model: string;
  operation:
    | 'chat.completions'
    | 'messages'
    | 'responses'
    | 'embeddings'
    | 'images'
    | 'speech'
    | 'transcriptions'
    | 'videos'
    | 'rerank';
  inputTokens: number;
  outputTokens: number;
  cachedInputTokens?: number | null;
  cacheWriteTokens?: number | null;
  reasoningTokens?: number | null;
  totalTokens: number;
  costUSD: number;
  finishReason?: string | null;
  requestedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats".
 */
export interface Chat {
  id: number;
  title?: string | null;
  user?: (number | null) | User;
  agent?: string | null;
  lastMessageAt?: string | null;
  todos?: import('frogbot/tools').TodoItem[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  chat: number | Chat;
  role: 'user' | 'assistant' | 'system';
  parts: import('frogbot').UIMessage['parts'];
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usage?: {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
    reasoningTokens?: number | null;
    cachedInputTokens?: number | null;
    model?: string | null;
    provider?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  owner: number | User;
  piece: string;
  method: 'oauth' | 'secret';
  credential: string;
  account?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scopes?: string[] | null;
  expiresAt?: string | null;
  status: 'active' | 'error' | 'revoked';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-trigger-subscriptions".
 */
export interface FrogbotTriggerSubscription {
  id: number;
  agent: string;
  piece: string;
  instance: string;
  trigger: string;
  inputHash: string;
  input:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  webhookUrl?: string | null;
  status: 'active' | 'error';
  cleanupPending?: boolean | null;
  enablePending?: boolean | null;
  enableAttempt?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  name?: boolean;
  modelAccess?: boolean;
  models?: boolean;
  monthlyBudget?: boolean;
  spendThisPeriodUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect {
  alt?: boolean;
  folder?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect {
  name?: boolean;
  version?: boolean;
  status?: boolean;
  targetDate?: boolean;
  owner?: boolean;
  summary?: boolean;
  acceptanceCriteria?: boolean;
  releaseNotes?: boolean;
  artifacts?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect {
  name?: boolean;
  owner?: boolean;
  prefix?: boolean;
  tokenHash?: boolean;
  lastUsedAt?: boolean;
  revokedAt?: boolean;
  totalCostUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs_select".
 */
export interface UsageLogsSelect {
  apiKey?: boolean;
  user?: boolean;
  chat?: boolean;
  requestId?: boolean;
  runId?: boolean;
  model?: boolean;
  operation?: boolean;
  inputTokens?: boolean;
  outputTokens?: boolean;
  cachedInputTokens?: boolean;
  cacheWriteTokens?: boolean;
  reasoningTokens?: boolean;
  totalTokens?: boolean;
  costUSD?: boolean;
  finishReason?: boolean;
  requestedAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats_select".
 */
export interface ChatsSelect {
  title?: boolean;
  user?: boolean;
  agent?: boolean;
  lastMessageAt?: boolean;
  todos?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect {
  id?: boolean;
  chat?: boolean;
  role?: boolean;
  parts?: boolean;
  metadata?: boolean;
  usage?:
    | boolean
    | {
        inputTokens?: boolean;
        outputTokens?: boolean;
        totalTokens?: boolean;
        reasoningTokens?: boolean;
        cachedInputTokens?: boolean;
        model?: boolean;
        provider?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect {
  owner?: boolean;
  piece?: boolean;
  method?: boolean;
  credential?: boolean;
  account?: boolean;
  scopes?: boolean;
  expiresAt?: boolean;
  status?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-trigger-subscriptions_select".
 */
export interface FrogbotTriggerSubscriptionsSelect {
  agent?: boolean;
  piece?: boolean;
  instance?: boolean;
  trigger?: boolean;
  inputHash?: boolean;
  input?: boolean;
  state?: boolean;
  webhookUrl?: boolean;
  status?: boolean;
  cleanupPending?: boolean;
  enablePending?: boolean;
  enableAttempt?: boolean;
  expiresAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogbot-reset-ai-budgets".
 */
export interface TaskFrogbotResetAiBudgets {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogbot-cleanup-kv".
 */
export interface TaskFrogbotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {
      'qa-analyst': unknown;
      'release-manager': unknown;
    };
    models:
      | 'openai/chatgpt-image-latest'
      | 'openai/gpt-4.1'
      | 'openai/gpt-4.1-mini'
      | 'openai/gpt-4o'
      | 'openai/gpt-4o-2024-08-06'
      | 'openai/gpt-4o-2024-11-20'
      | 'openai/gpt-4o-mini'
      | 'openai/gpt-5'
      | 'openai/gpt-5-mini'
      | 'openai/gpt-5-nano'
      | 'openai/gpt-5-pro'
      | 'openai/gpt-5.1'
      | 'openai/gpt-5.2'
      | 'openai/gpt-5.2-chat-latest'
      | 'openai/gpt-5.2-pro'
      | 'openai/gpt-5.3-chat-latest'
      | 'openai/gpt-5.3-codex'
      | 'openai/gpt-5.3-codex-spark'
      | 'openai/gpt-5.4'
      | 'openai/gpt-5.4-mini'
      | 'openai/gpt-5.4-nano'
      | 'openai/gpt-5.4-pro'
      | 'openai/gpt-5.5'
      | 'openai/gpt-5.5-pro'
      | 'openai/gpt-5.6'
      | 'openai/gpt-5.6-luna'
      | 'openai/gpt-5.6-sol'
      | 'openai/gpt-5.6-terra'
      | 'openai/gpt-image-1-mini'
      | 'openai/gpt-image-1.5'
      | 'openai/gpt-image-2'
      | 'openai/gpt-realtime-2.1'
      | 'openai/o3'
      | 'openai/o3-pro'
      | 'openai/text-embedding-3-large'
      | 'openai/text-embedding-3-small'
      | 'openai/text-embedding-ada-002';
    roles: never;
  }
}
