/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    messages: Message;
    tasks: Task;
    projects: Project;
    tags: Tag;
    timesheets: Timesheet;
    'api-keys': ApiKey;
    'usage-logs': UsageLog;
    chats: Chat;
    'frogbot-chat-assets': FrogBotChatAsset;
    'frogbot-chat-turns': FrogBotChatTurn;
    'frogbot-waitpoints': FrogBotWaitpoint;
    'frogbot-autonumbers': FrogBotAutonumber;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    messages: MessagesSelect;
    tasks: TasksSelect;
    projects: ProjectsSelect;
    tags: TagsSelect;
    timesheets: TimesheetsSelect;
    'api-keys': ApiKeysSelect;
    'usage-logs': UsageLogsSelect;
    chats: ChatsSelect;
    'frogbot-chat-assets': FrogBotChatAssetsSelect;
    'frogbot-chat-turns': FrogBotChatTurnsSelect;
    'frogbot-waitpoints': FrogBotWaitpointsSelect;
    'frogbot-autonumbers': FrogBotAutonumbersSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'frogbot-reset-ai-budgets': TaskFrogBotResetAiBudgets;
      'frogbot-sweep-jobs': TaskFrogBotSweepJobs;
      'frogbot-cleanup-kv': TaskFrogBotCleanupKv;
      'frogbot-run-ai-field': TaskFrogBotRunAIField;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  modelAccess?: ('all' | 'selected') | null;
  models?:
    | (
        | 'bedrock/amazon.nova-lite-v1:0'
        | 'bedrock/amazon.nova-micro-v1:0'
        | 'bedrock/amazon.nova-pro-v1:0'
        | 'bedrock/anthropic.claude-fable-5'
        | 'bedrock/anthropic.claude-fable-5-1'
        | 'bedrock/anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/anthropic.claude-opus-4-5-20251101-v1:0'
        | 'bedrock/anthropic.claude-opus-4-6-v1'
        | 'bedrock/anthropic.claude-opus-4-7'
        | 'bedrock/anthropic.claude-opus-4-8'
        | 'bedrock/anthropic.claude-opus-5'
        | 'bedrock/anthropic.claude-opus-5-5'
        | 'bedrock/anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/anthropic.claude-sonnet-4-6'
        | 'bedrock/anthropic.claude-sonnet-5'
        | 'bedrock/anthropic.claude-sonnet-5-5'
        | 'bedrock/apac.amazon.nova-lite-v1:0'
        | 'bedrock/apac.amazon.nova-micro-v1:0'
        | 'bedrock/apac.amazon.nova-pro-v1:0'
        | 'bedrock/au.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/au.anthropic.claude-opus-4-6-v1'
        | 'bedrock/au.anthropic.claude-opus-4-7'
        | 'bedrock/au.anthropic.claude-opus-4-8'
        | 'bedrock/au.anthropic.claude-opus-5'
        | 'bedrock/au.anthropic.claude-opus-5-5'
        | 'bedrock/au.anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/au.anthropic.claude-sonnet-4-6'
        | 'bedrock/au.anthropic.claude-sonnet-5'
        | 'bedrock/ca.amazon.nova-lite-v1:0'
        | 'bedrock/deepseek.r1-v1:0'
        | 'bedrock/deepseek.v3-v1:0'
        | 'bedrock/deepseek.v3.2'
        | 'bedrock/eu.amazon.nova-2-lite-v1:0'
        | 'bedrock/eu.amazon.nova-lite-v1:0'
        | 'bedrock/eu.amazon.nova-micro-v1:0'
        | 'bedrock/eu.amazon.nova-pro-v1:0'
        | 'bedrock/eu.anthropic.claude-fable-5'
        | 'bedrock/eu.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/eu.anthropic.claude-opus-4-5-20251101-v1:0'
        | 'bedrock/eu.anthropic.claude-opus-4-6-v1'
        | 'bedrock/eu.anthropic.claude-opus-4-7'
        | 'bedrock/eu.anthropic.claude-opus-4-8'
        | 'bedrock/eu.anthropic.claude-opus-5'
        | 'bedrock/eu.anthropic.claude-opus-5-5'
        | 'bedrock/eu.anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/eu.anthropic.claude-sonnet-4-6'
        | 'bedrock/eu.anthropic.claude-sonnet-5'
        | 'bedrock/eu.anthropic.claude-sonnet-5-5'
        | 'bedrock/eu.mistral.pixtral-large-2502-v1:0'
        | 'bedrock/global.amazon.nova-2-lite-v1:0'
        | 'bedrock/global.anthropic.claude-fable-5'
        | 'bedrock/global.anthropic.claude-fable-5-1'
        | 'bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/global.anthropic.claude-opus-4-5-20251101-v1:0'
        | 'bedrock/global.anthropic.claude-opus-4-6-v1'
        | 'bedrock/global.anthropic.claude-opus-4-7'
        | 'bedrock/global.anthropic.claude-opus-4-8'
        | 'bedrock/global.anthropic.claude-opus-5'
        | 'bedrock/global.anthropic.claude-opus-5-5'
        | 'bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/global.anthropic.claude-sonnet-4-6'
        | 'bedrock/global.anthropic.claude-sonnet-5'
        | 'bedrock/global.anthropic.claude-sonnet-5-5'
        | 'bedrock/global.moonshotai.kimi-k3'
        | 'bedrock/global.openai.gpt-5.6-luna'
        | 'bedrock/global.openai.gpt-5.6-sol'
        | 'bedrock/global.openai.gpt-5.6-terra'
        | 'bedrock/global.openai.gpt-6-astra'
        | 'bedrock/global.openai.gpt-6-luna'
        | 'bedrock/global.openai.gpt-6-sol'
        | 'bedrock/global.openai.gpt-6.1-sol'
        | 'bedrock/global.xai.grok-4.6'
        | 'bedrock/global.xai.grok-4.7'
        | 'bedrock/google.gemma-3-12b-it'
        | 'bedrock/google.gemma-3-27b-it'
        | 'bedrock/google.gemma-3-4b-it'
        | 'bedrock/google.gemma-4-26b-a4b'
        | 'bedrock/google.gemma-4-31b'
        | 'bedrock/google.gemma-4-e2b'
        | 'bedrock/in.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/in.anthropic.claude-opus-5'
        | 'bedrock/in.anthropic.claude-sonnet-5'
        | 'bedrock/in.openai.gpt-5.6-luna'
        | 'bedrock/in.openai.gpt-5.6-terra'
        | 'bedrock/jp.amazon.nova-2-lite-v1:0'
        | 'bedrock/jp.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/jp.anthropic.claude-opus-4-7'
        | 'bedrock/jp.anthropic.claude-opus-4-8'
        | 'bedrock/jp.anthropic.claude-opus-5'
        | 'bedrock/jp.anthropic.claude-opus-5-5'
        | 'bedrock/jp.anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/jp.anthropic.claude-sonnet-4-6'
        | 'bedrock/jp.anthropic.claude-sonnet-5'
        | 'bedrock/meta.llama3-1-70b-instruct-v1:0'
        | 'bedrock/meta.llama4-maverick-17b-instruct-v1:0'
        | 'bedrock/meta.llama4-scout-17b-instruct-v1:0'
        | 'bedrock/minimax.minimax-m2'
        | 'bedrock/minimax.minimax-m2.1'
        | 'bedrock/minimax.minimax-m2.5'
        | 'bedrock/mistral.devstral-2-123b'
        | 'bedrock/mistral.magistral-small-2509'
        | 'bedrock/mistral.ministral-3-14b-instruct'
        | 'bedrock/mistral.ministral-3-3b-instruct'
        | 'bedrock/mistral.ministral-3-8b-instruct'
        | 'bedrock/mistral.mistral-large-3-675b-instruct'
        | 'bedrock/mistral.pixtral-large-2502-v1:0'
        | 'bedrock/mistral.voxtral-mini-3b-2507'
        | 'bedrock/mistral.voxtral-small-24b-2507'
        | 'bedrock/moonshot.kimi-k2-thinking'
        | 'bedrock/moonshotai.kimi-k2.5'
        | 'bedrock/nvidia.nemotron-nano-12b-v2'
        | 'bedrock/nvidia.nemotron-nano-3-30b'
        | 'bedrock/nvidia.nemotron-nano-9b-v2'
        | 'bedrock/nvidia.nemotron-super-3-120b'
        | 'bedrock/openai.gpt-5.4'
        | 'bedrock/openai.gpt-5.5'
        | 'bedrock/openai.gpt-5.6-luna'
        | 'bedrock/openai.gpt-5.6-sol'
        | 'bedrock/openai.gpt-5.6-terra'
        | 'bedrock/openai.gpt-6-astra'
        | 'bedrock/openai.gpt-6-luna'
        | 'bedrock/openai.gpt-6-sol'
        | 'bedrock/openai.gpt-6.1-sol'
        | 'bedrock/openai.gpt-oss-120b'
        | 'bedrock/openai.gpt-oss-120b-1:0'
        | 'bedrock/openai.gpt-oss-20b'
        | 'bedrock/openai.gpt-oss-20b-1:0'
        | 'bedrock/openai.gpt-oss-safeguard-120b'
        | 'bedrock/openai.gpt-oss-safeguard-20b'
        | 'bedrock/qwen.qwen3-235b-a22b-2507-v1:0'
        | 'bedrock/qwen.qwen3-32b-v1:0'
        | 'bedrock/qwen.qwen3-coder-30b-a3b-v1:0'
        | 'bedrock/qwen.qwen3-coder-480b-a35b-v1:0'
        | 'bedrock/qwen.qwen3-coder-next'
        | 'bedrock/qwen.qwen3-next-80b-a3b'
        | 'bedrock/qwen.qwen3-vl-235b-a22b'
        | 'bedrock/us-gov.openai.gpt-oss-120b-1:0'
        | 'bedrock/us-gov.openai.gpt-oss-20b-1:0'
        | 'bedrock/us.amazon.nova-2-lite-v1:0'
        | 'bedrock/us.amazon.nova-lite-v1:0'
        | 'bedrock/us.amazon.nova-micro-v1:0'
        | 'bedrock/us.amazon.nova-pro-v1:0'
        | 'bedrock/us.anthropic.claude-fable-5'
        | 'bedrock/us.anthropic.claude-fable-5-1'
        | 'bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0'
        | 'bedrock/us.anthropic.claude-opus-4-5-20251101-v1:0'
        | 'bedrock/us.anthropic.claude-opus-4-6-v1'
        | 'bedrock/us.anthropic.claude-opus-4-7'
        | 'bedrock/us.anthropic.claude-opus-4-8'
        | 'bedrock/us.anthropic.claude-opus-5'
        | 'bedrock/us.anthropic.claude-opus-5-5'
        | 'bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0'
        | 'bedrock/us.anthropic.claude-sonnet-4-6'
        | 'bedrock/us.anthropic.claude-sonnet-5'
        | 'bedrock/us.anthropic.claude-sonnet-5-5'
        | 'bedrock/us.deepseek.r1-v1:0'
        | 'bedrock/us.meta.llama3-1-70b-instruct-v1:0'
        | 'bedrock/us.meta.llama3-1-8b-instruct-v1:0'
        | 'bedrock/us.meta.llama3-3-70b-instruct-v1:0'
        | 'bedrock/us.meta.llama4-maverick-17b-instruct-v1:0'
        | 'bedrock/us.meta.llama4-scout-17b-instruct-v1:0'
        | 'bedrock/us.mistral.pixtral-large-2502-v1:0'
        | 'bedrock/us.moonshotai.kimi-k3'
        | 'bedrock/us.openai.gpt-5.6-luna'
        | 'bedrock/us.openai.gpt-5.6-sol'
        | 'bedrock/us.openai.gpt-5.6-terra'
        | 'bedrock/us.openai.gpt-6-astra'
        | 'bedrock/us.openai.gpt-6-luna'
        | 'bedrock/us.openai.gpt-6-sol'
        | 'bedrock/us.openai.gpt-6.1-sol'
        | 'bedrock/us.writer.palmyra-x4-v1:0'
        | 'bedrock/us.writer.palmyra-x5-v1:0'
        | 'bedrock/us.xai.grok-4.6'
        | 'bedrock/us.xai.grok-4.7'
        | 'bedrock/writer.palmyra-x4-v1:0'
        | 'bedrock/writer.palmyra-x5-v1:0'
        | 'bedrock/xai.grok-4.3'
        | 'bedrock/xai.grok-4.6'
        | 'bedrock/zai.glm-4.7'
        | 'bedrock/zai.glm-4.7-flash'
        | 'bedrock/zai.glm-5'
        | 'browser/deliberator'
        | 'browser/questioner'
        | 'browser/sprinter'
        | 'browser/thinker'
        | 'browser/verbose'
        | 'openrouter/aion-labs/aion-2.0'
        | 'openrouter/aion-labs/aion-3.0'
        | 'openrouter/aion-labs/aion-3.0-mini'
        | 'openrouter/aion-labs/aion-3.5'
        | 'openrouter/aion-labs/aion-3.5-mini'
        | 'openrouter/aion-labs/aion-rp-llama-3.1-8b'
        | 'openrouter/amazon/nova-2-lite-v1'
        | 'openrouter/amazon/nova-lite-v1'
        | 'openrouter/amazon/nova-micro-v1'
        | 'openrouter/amazon/nova-premier-v1'
        | 'openrouter/amazon/nova-pro-v1'
        | 'openrouter/anthracite-org/magnum-v4-72b'
        | 'openrouter/anthropic/claude-fable-5'
        | 'openrouter/anthropic/claude-fable-5.1'
        | 'openrouter/anthropic/claude-haiku-4.5'
        | 'openrouter/anthropic/claude-opus-4.1'
        | 'openrouter/anthropic/claude-opus-4.5'
        | 'openrouter/anthropic/claude-opus-4.6'
        | 'openrouter/anthropic/claude-opus-4.7'
        | 'openrouter/anthropic/claude-opus-4.8'
        | 'openrouter/anthropic/claude-opus-5'
        | 'openrouter/anthropic/claude-opus-5.5'
        | 'openrouter/anthropic/claude-sonnet-4'
        | 'openrouter/anthropic/claude-sonnet-4.5'
        | 'openrouter/anthropic/claude-sonnet-4.6'
        | 'openrouter/anthropic/claude-sonnet-5'
        | 'openrouter/anthropic/claude-sonnet-5.5'
        | 'openrouter/apodex/apodex-1.1-mini:free'
        | 'openrouter/arcee-ai/trinity-large-thinking'
        | 'openrouter/baidu/ernie-4.5-vl-424b-a47b'
        | 'openrouter/bytedance-seed/seed-1.6'
        | 'openrouter/bytedance-seed/seed-1.6-flash'
        | 'openrouter/bytedance-seed/seed-2-1-turbo'
        | 'openrouter/bytedance-seed/seed-2.0-code'
        | 'openrouter/bytedance-seed/seed-2.0-lite'
        | 'openrouter/bytedance-seed/seed-2.0-mini'
        | 'openrouter/bytedance/ui-tars-1.5-7b'
        | 'openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition'
        | 'openrouter/cohere/command-a'
        | 'openrouter/cohere/command-a-plus'
        | 'openrouter/cohere/command-r-08-2024'
        | 'openrouter/cohere/command-r-plus-08-2024'
        | 'openrouter/cohere/command-r7b-12-2024'
        | 'openrouter/cohere/north-mini-code:free'
        | 'openrouter/deepseek/deepseek-chat'
        | 'openrouter/deepseek/deepseek-chat-v3-0324'
        | 'openrouter/deepseek/deepseek-chat-v3.1'
        | 'openrouter/deepseek/deepseek-r1'
        | 'openrouter/deepseek/deepseek-r1-0528'
        | 'openrouter/deepseek/deepseek-v3.1-terminus'
        | 'openrouter/deepseek/deepseek-v3.2'
        | 'openrouter/deepseek/deepseek-v3.2-exp'
        | 'openrouter/deepseek/deepseek-v4-flash'
        | 'openrouter/deepseek/deepseek-v4-flash-0731'
        | 'openrouter/deepseek/deepseek-v4-flash-vision-exp'
        | 'openrouter/deepseek/deepseek-v4-pro'
        | 'openrouter/deepseek/deepseek-v4-pro-0813'
        | 'openrouter/deepseek/deepseek-v4.1-flash'
        | 'openrouter/dots-studio/dots-3-note-preview:free'
        | 'openrouter/fireworks/ember-1'
        | 'openrouter/google/gemini-2.5-flash'
        | 'openrouter/google/gemini-2.5-flash-lite'
        | 'openrouter/google/gemini-2.5-pro'
        | 'openrouter/google/gemini-2.5-pro-preview'
        | 'openrouter/google/gemini-3-flash-preview'
        | 'openrouter/google/gemini-3.1-flash-lite'
        | 'openrouter/google/gemini-3.1-flash-lite-preview'
        | 'openrouter/google/gemini-3.1-pro-preview'
        | 'openrouter/google/gemini-3.1-pro-preview-customtools'
        | 'openrouter/google/gemini-3.5-flash'
        | 'openrouter/google/gemini-3.5-flash-lite'
        | 'openrouter/google/gemini-3.6-flash'
        | 'openrouter/google/gemini-3.7-flash'
        | 'openrouter/google/gemini-3.8-flash'
        | 'openrouter/google/gemma-2-27b-it'
        | 'openrouter/google/gemma-3-12b-it'
        | 'openrouter/google/gemma-3-27b-it'
        | 'openrouter/google/gemma-3-4b-it'
        | 'openrouter/google/gemma-4-26b-a4b-it'
        | 'openrouter/google/gemma-4-26b-a4b-it:free'
        | 'openrouter/google/gemma-4-31b-it'
        | 'openrouter/google/gemma-4-31b-it:free'
        | 'openrouter/gryphe/mythomax-l2-13b'
        | 'openrouter/ibm-granite/granite-4.0-h-micro'
        | 'openrouter/ibm-granite/granite-4.2-8b'
        | 'openrouter/inception/mercury-2'
        | 'openrouter/inception/mercury-2.5'
        | 'openrouter/inclusionai/ling-3.0-flash'
        | 'openrouter/inclusionai/ling-3.0-flash-fin'
        | 'openrouter/inclusionai/ling-3.0-flash-sante:free'
        | 'openrouter/inclusionai/ling-3.0-flash-vl'
        | 'openrouter/inclusionai/ling-3.1-flash'
        | 'openrouter/inference-net/schematron-v2-small'
        | 'openrouter/inference-net/schematron-v2-turbo'
        | 'openrouter/kwaipilot/kat-coder-pro-v2.5'
        | 'openrouter/liquid/lfm-2.5-2.6b:free'
        | 'openrouter/mancer/weaver'
        | 'openrouter/meituan/longcat-2.0'
        | 'openrouter/meta-llama/llama-3.1-70b-instruct'
        | 'openrouter/meta-llama/llama-3.1-8b-instruct'
        | 'openrouter/meta-llama/llama-3.2-1b-instruct'
        | 'openrouter/meta-llama/llama-3.2-3b-instruct'
        | 'openrouter/meta-llama/llama-3.3-70b-instruct'
        | 'openrouter/meta-llama/llama-4-maverick'
        | 'openrouter/meta-llama/llama-4-scout'
        | 'openrouter/meta-llama/llama-guard-4-12b'
        | 'openrouter/meta/muse-glimmer-30b'
        | 'openrouter/meta/muse-spark-1.1'
        | 'openrouter/meta/muse-spark-1.2'
        | 'openrouter/meta/muse-spark-1.2-contributor'
        | 'openrouter/meta/muse-spark-1.3'
        | 'openrouter/meta/muse-spark-1.3-contributor'
        | 'openrouter/microsoft/phi-4'
        | 'openrouter/microsoft/wizardlm-2-8x22b'
        | 'openrouter/minimax/minimax-01'
        | 'openrouter/minimax/minimax-m1'
        | 'openrouter/minimax/minimax-m2'
        | 'openrouter/minimax/minimax-m2-her'
        | 'openrouter/minimax/minimax-m2.1'
        | 'openrouter/minimax/minimax-m2.5'
        | 'openrouter/minimax/minimax-m2.7'
        | 'openrouter/minimax/minimax-m3'
        | 'openrouter/mistralai/codestral-2508'
        | 'openrouter/mistralai/devstral-2512'
        | 'openrouter/mistralai/ministral-14b-2512'
        | 'openrouter/mistralai/ministral-3b-2512'
        | 'openrouter/mistralai/ministral-8b-2512'
        | 'openrouter/mistralai/mistral-large'
        | 'openrouter/mistralai/mistral-large-2407'
        | 'openrouter/mistralai/mistral-large-2512'
        | 'openrouter/mistralai/mistral-medium-3'
        | 'openrouter/mistralai/mistral-medium-3-5'
        | 'openrouter/mistralai/mistral-medium-3.1'
        | 'openrouter/mistralai/mistral-nemo'
        | 'openrouter/mistralai/mistral-saba'
        | 'openrouter/mistralai/mistral-small-24b-instruct-2501'
        | 'openrouter/mistralai/mistral-small-2603'
        | 'openrouter/mistralai/mistral-small-3.1-24b-instruct'
        | 'openrouter/mistralai/mistral-small-3.2-24b-instruct'
        | 'openrouter/mistralai/mixtral-8x22b-instruct'
        | 'openrouter/mistralai/voxtral-small-24b-2507'
        | 'openrouter/moonshotai/kimi-k2'
        | 'openrouter/moonshotai/kimi-k2-0905'
        | 'openrouter/moonshotai/kimi-k2-thinking'
        | 'openrouter/moonshotai/kimi-k2.5'
        | 'openrouter/moonshotai/kimi-k2.6'
        | 'openrouter/moonshotai/kimi-k2.7-code'
        | 'openrouter/moonshotai/kimi-k3'
        | 'openrouter/morph/morph-v3-fast'
        | 'openrouter/morph/morph-v3-large'
        | 'openrouter/nex-agi/nex-n2.5-mini'
        | 'openrouter/nex-agi/nex-n2.5-pro'
        | 'openrouter/nousresearch/hermes-3-llama-3.1-405b'
        | 'openrouter/nousresearch/hermes-3-llama-3.1-70b'
        | 'openrouter/nousresearch/hermes-4-405b'
        | 'openrouter/nvidia/nemotron-3-nano-30b-a3b'
        | 'openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free'
        | 'openrouter/nvidia/nemotron-3-super-120b-a12b'
        | 'openrouter/nvidia/nemotron-3-super-120b-a12b:free'
        | 'openrouter/nvidia/nemotron-3-ultra-550b-a55b'
        | 'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free'
        | 'openrouter/nvidia/nemotron-3.5-content-safety'
        | 'openrouter/nvidia/nemotron-3.5-content-safety:free'
        | 'openrouter/nvidia/nemotron-3.5-lightning'
        | 'openrouter/nvidia/nemotron-3.5-lightning:free'
        | 'openrouter/openai/gpt-3.5-turbo'
        | 'openrouter/openai/gpt-3.5-turbo-0613'
        | 'openrouter/openai/gpt-3.5-turbo-16k'
        | 'openrouter/openai/gpt-3.5-turbo-instruct'
        | 'openrouter/openai/gpt-4'
        | 'openrouter/openai/gpt-4-turbo'
        | 'openrouter/openai/gpt-4.1'
        | 'openrouter/openai/gpt-4.1-mini'
        | 'openrouter/openai/gpt-4.1-nano'
        | 'openrouter/openai/gpt-4o'
        | 'openrouter/openai/gpt-4o-2024-05-13'
        | 'openrouter/openai/gpt-4o-2024-08-06'
        | 'openrouter/openai/gpt-4o-2024-11-20'
        | 'openrouter/openai/gpt-4o-mini'
        | 'openrouter/openai/gpt-4o-mini-2024-07-18'
        | 'openrouter/openai/gpt-5'
        | 'openrouter/openai/gpt-5-mini'
        | 'openrouter/openai/gpt-5-nano'
        | 'openrouter/openai/gpt-5-pro'
        | 'openrouter/openai/gpt-5.1'
        | 'openrouter/openai/gpt-5.1-codex'
        | 'openrouter/openai/gpt-5.1-codex-max'
        | 'openrouter/openai/gpt-5.1-codex-mini'
        | 'openrouter/openai/gpt-5.2'
        | 'openrouter/openai/gpt-5.2-chat'
        | 'openrouter/openai/gpt-5.2-codex'
        | 'openrouter/openai/gpt-5.2-pro'
        | 'openrouter/openai/gpt-5.3-codex'
        | 'openrouter/openai/gpt-5.4'
        | 'openrouter/openai/gpt-5.4-mini'
        | 'openrouter/openai/gpt-5.4-nano'
        | 'openrouter/openai/gpt-5.4-pro'
        | 'openrouter/openai/gpt-5.5'
        | 'openrouter/openai/gpt-5.5-pro'
        | 'openrouter/openai/gpt-5.6-luna'
        | 'openrouter/openai/gpt-5.6-luna-pro'
        | 'openrouter/openai/gpt-5.6-sol'
        | 'openrouter/openai/gpt-5.6-sol-pro'
        | 'openrouter/openai/gpt-5.6-terra'
        | 'openrouter/openai/gpt-5.6-terra-pro'
        | 'openrouter/openai/gpt-6-astra'
        | 'openrouter/openai/gpt-6-astra-pro'
        | 'openrouter/openai/gpt-6-luna'
        | 'openrouter/openai/gpt-6-luna-pro'
        | 'openrouter/openai/gpt-6-sol'
        | 'openrouter/openai/gpt-6-sol-pro'
        | 'openrouter/openai/gpt-6.1-sol'
        | 'openrouter/openai/gpt-6.1-sol-pro'
        | 'openrouter/openai/gpt-chat-latest'
        | 'openrouter/openai/gpt-oss-120b'
        | 'openrouter/openai/gpt-oss-20b'
        | 'openrouter/openai/gpt-oss-safeguard-20b'
        | 'openrouter/openai/o1'
        | 'openrouter/openai/o1-pro'
        | 'openrouter/openai/o3'
        | 'openrouter/openai/o3-mini'
        | 'openrouter/openai/o3-mini-high'
        | 'openrouter/openai/o3-pro'
        | 'openrouter/openai/o4-mini'
        | 'openrouter/openai/o4-mini-high'
        | 'openrouter/openrouter/free'
        | 'openrouter/perceptron/perceptron-mk1'
        | 'openrouter/perceptron/perceptron-mk1.5'
        | 'openrouter/perplexity/sonar'
        | 'openrouter/perplexity/sonar-deep-research'
        | 'openrouter/perplexity/sonar-pro'
        | 'openrouter/perplexity/sonar-pro-search'
        | 'openrouter/perplexity/sonar-reasoning-pro'
        | 'openrouter/poolside/laguna-s-2.1'
        | 'openrouter/poolside/laguna-s-2.1:free'
        | 'openrouter/poolside/laguna-xs-2.1'
        | 'openrouter/poolside/laguna-xs-2.1:free'
        | 'openrouter/prism-ml/ternary-bonsai-2-27b'
        | 'openrouter/qwen/qwen-2.5-72b-instruct'
        | 'openrouter/qwen/qwen-2.5-7b-instruct'
        | 'openrouter/qwen/qwen-2.5-coder-32b-instruct'
        | 'openrouter/qwen/qwen-plus'
        | 'openrouter/qwen/qwen-plus-2025-07-28'
        | 'openrouter/qwen/qwen2.5-vl-72b-instruct'
        | 'openrouter/qwen/qwen3-14b'
        | 'openrouter/qwen/qwen3-235b-a22b'
        | 'openrouter/qwen/qwen3-235b-a22b-2507'
        | 'openrouter/qwen/qwen3-235b-a22b-thinking-2507'
        | 'openrouter/qwen/qwen3-30b-a3b'
        | 'openrouter/qwen/qwen3-30b-a3b-instruct-2507'
        | 'openrouter/qwen/qwen3-30b-a3b-thinking-2507'
        | 'openrouter/qwen/qwen3-32b'
        | 'openrouter/qwen/qwen3-8b'
        | 'openrouter/qwen/qwen3-coder'
        | 'openrouter/qwen/qwen3-coder-30b-a3b-instruct'
        | 'openrouter/qwen/qwen3-coder-flash'
        | 'openrouter/qwen/qwen3-coder-next'
        | 'openrouter/qwen/qwen3-coder-plus'
        | 'openrouter/qwen/qwen3-max'
        | 'openrouter/qwen/qwen3-max-thinking'
        | 'openrouter/qwen/qwen3-next-80b-a3b-instruct'
        | 'openrouter/qwen/qwen3-next-80b-a3b-thinking'
        | 'openrouter/qwen/qwen3-vl-235b-a22b-instruct'
        | 'openrouter/qwen/qwen3-vl-235b-a22b-thinking'
        | 'openrouter/qwen/qwen3-vl-30b-a3b-instruct'
        | 'openrouter/qwen/qwen3-vl-30b-a3b-thinking'
        | 'openrouter/qwen/qwen3-vl-32b-instruct'
        | 'openrouter/qwen/qwen3-vl-8b-instruct'
        | 'openrouter/qwen/qwen3-vl-8b-thinking'
        | 'openrouter/qwen/qwen3.5-122b-a10b'
        | 'openrouter/qwen/qwen3.5-27b'
        | 'openrouter/qwen/qwen3.5-35b-a3b'
        | 'openrouter/qwen/qwen3.5-397b-a17b'
        | 'openrouter/qwen/qwen3.5-9b'
        | 'openrouter/qwen/qwen3.5-flash-02-23'
        | 'openrouter/qwen/qwen3.5-plus-02-15'
        | 'openrouter/qwen/qwen3.5-plus-20260420'
        | 'openrouter/qwen/qwen3.6-27b'
        | 'openrouter/qwen/qwen3.6-35b-a3b'
        | 'openrouter/qwen/qwen3.6-flash'
        | 'openrouter/qwen/qwen3.6-max-preview'
        | 'openrouter/qwen/qwen3.6-plus'
        | 'openrouter/qwen/qwen3.7-flash'
        | 'openrouter/qwen/qwen3.7-max'
        | 'openrouter/qwen/qwen3.7-plus'
        | 'openrouter/qwen/qwen3.8-2.4t-a95b'
        | 'openrouter/qwen/qwen3.8-27b'
        | 'openrouter/qwen/qwen3.8-27b:free'
        | 'openrouter/qwen/qwen3.8-flash'
        | 'openrouter/qwen/qwen3.8-max-0902'
        | 'openrouter/qwen/qwen3.8-max-prime'
        | 'openrouter/qwen/qwen3.8-omni-flash'
        | 'openrouter/rekaai/reka-edge'
        | 'openrouter/rekaai/reka-flash-3'
        | 'openrouter/relace/relace-apply-3'
        | 'openrouter/relace/relace-search'
        | 'openrouter/sakana/fugu-max'
        | 'openrouter/sakana/fugu-ultra'
        | 'openrouter/sakana/fugu-ultra-v2'
        | 'openrouter/sakana/sakana-namazu'
        | 'openrouter/sao10k/l3-lunaris-8b'
        | 'openrouter/sao10k/l3.1-euryale-70b'
        | 'openrouter/sao10k/l3.3-euryale-70b'
        | 'openrouter/stealth/space-bunny-alpha'
        | 'openrouter/stepfun/step-3.5-flash'
        | 'openrouter/stepfun/step-3.7-flash'
        | 'openrouter/tencent/hunyuan-a13b-instruct'
        | 'openrouter/tencent/hy-mt2-1.8b'
        | 'openrouter/tencent/hy-mt2-30b-a3b'
        | 'openrouter/tencent/hy-mt2-7b'
        | 'openrouter/tencent/hy3'
        | 'openrouter/tencent/hy3-preview'
        | 'openrouter/tencent/hy4-preview'
        | 'openrouter/thedrummer/cydonia-24b-v4.1'
        | 'openrouter/thedrummer/skyfall-36b-v2'
        | 'openrouter/thedrummer/unslopnemo-12b'
        | 'openrouter/thinkingmachines/inkling'
        | 'openrouter/thinkingmachines/inkling-small'
        | 'openrouter/thinkingmachines/inkling-small:free'
        | 'openrouter/thinkingmachines/inkling:free'
        | 'openrouter/unbiased/pareto'
        | 'openrouter/unbiased/pareto-26.10-preview'
        | 'openrouter/undi95/remm-slerp-l2-13b'
        | 'openrouter/upstage/solar-mini4'
        | 'openrouter/upstage/solar-pro-3'
        | 'openrouter/upstage/solar-pro4'
        | 'openrouter/writer/palmyra-x5'
        | 'openrouter/x-ai/grok-4.20'
        | 'openrouter/x-ai/grok-4.20-multi-agent'
        | 'openrouter/x-ai/grok-4.3'
        | 'openrouter/x-ai/grok-4.5'
        | 'openrouter/x-ai/grok-4.6'
        | 'openrouter/x-ai/grok-4.7'
        | 'openrouter/x-ai/grok-build-0.1'
        | 'openrouter/xiaomi/mimo-v2.5'
        | 'openrouter/xiaomi/mimo-v2.5-pro'
        | 'openrouter/xiaomi/mimo-v2.6-flash'
        | 'openrouter/xiaomi/mimo-v2.6-pro'
        | 'openrouter/xiaomi/mimo-v2.6-pro-ultraspeed'
        | 'openrouter/z-ai/glm-4.5'
        | 'openrouter/z-ai/glm-4.5-air'
        | 'openrouter/z-ai/glm-4.5v'
        | 'openrouter/z-ai/glm-4.6'
        | 'openrouter/z-ai/glm-4.6v'
        | 'openrouter/z-ai/glm-4.7'
        | 'openrouter/z-ai/glm-4.7-flash'
        | 'openrouter/z-ai/glm-5'
        | 'openrouter/z-ai/glm-5-turbo'
        | 'openrouter/z-ai/glm-5.1'
        | 'openrouter/z-ai/glm-5.2'
        | 'openrouter/z-ai/glm-5.3'
        | 'openrouter/z-ai/glm-5.3-flash'
        | 'openrouter/z-ai/glm-5.3-flashx'
        | 'openrouter/z-ai/glm-5.3-prime'
        | 'openrouter/z-ai/glm-5v-turbo'
        | 'openrouter/~anthropic/claude-fable-latest'
        | 'openrouter/~anthropic/claude-haiku-latest'
        | 'openrouter/~anthropic/claude-opus-latest'
        | 'openrouter/~anthropic/claude-sonnet-latest'
        | 'openrouter/~deepseek/deepseek-flash-latest'
        | 'openrouter/~deepseek/deepseek-pro-latest'
        | 'openrouter/~deepseek/deepseek-v4-flash-latest'
        | 'openrouter/~google/gemini-flash-latest'
        | 'openrouter/~google/gemini-pro-latest'
        | 'openrouter/~moonshotai/kimi-latest'
        | 'openrouter/~openai/gpt-astra-latest'
        | 'openrouter/~openai/gpt-luna-latest'
        | 'openrouter/~openai/gpt-mini-latest'
        | 'openrouter/~openai/gpt-sol-latest'
        | 'openrouter/~openai/gpt-terra-latest'
        | 'openrouter/~x-ai/grok-latest'
        | 'openrouter/~z-ai/glm-flash-latest'
        | 'openrouter/~z-ai/glm-latest'
      )[]
    | null;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  monthlyBudget?: number | null;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  spendThisPeriodUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  chat: number | Chat;
  role: 'user' | 'assistant' | 'system';
  parts: import('frogbot').UIMessage['parts'];
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('active' | 'queued') | null;
  delivery?: ('queue' | 'steer') | null;
  model?: string | null;
  reasoning?: string | null;
  author?: import('frogbot').TurnActor;
  settlements?: Record<string, import('frogbot').ClientToolSettlement>;
  version?: number | null;
  usage?: {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
    reasoningTokens?: number | null;
    cachedInputTokens?: number | null;
    model?: string | null;
    provider?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats".
 */
export interface Chat {
  id: number;
  title?: string | null;
  user?: (number | null) | User;
  agent?: string | null;
  channel?: string | null;
  externalId?: string | null;
  channelKey?: string | null;
  channelThread?: import('frogbot').ChannelThreadReference;
  channelLabel?: string | null;
  lastMessageAt?: string | null;
  todos?: import('frogbot/tools').TodoItem[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  _order?: string | null;
  title: string;
  status?: ('backlog' | 'done') | null;
  channel?: string | null;
  dueAt?: string | null;
  labels?:
    | (
        | 'gray'
        | 'blue'
        | 'cyan'
        | 'teal'
        | 'green'
        | 'yellow'
        | 'orange'
        | 'red'
        | 'pink'
        | 'purple'
      )[]
    | null;
  /**
   * Fraction where 1 means 100%, for example 0.42 for 42%
   */
  progress?: number | null;
  /**
   * Whole-number rating from 1 to 5
   */
  score?: number | null;
  /**
   * Duration in whole seconds, for example 5400 for 1 hour 30 minutes
   */
  timeSpent?: number | null;
  /**
   * Web address, for example https://example.com or example.com
   */
  website?: string | null;
  /**
   * Phone number as text, for example +44 20 7946 0958 or (415) 555-9876
   */
  phone?: string | null;
  /**
   * Barcode value as text, for example a UPC or EAN code
   */
  sku?: string | null;
  /**
   * Unique number set by FrogBot when the record is created; read-only
   */
  number?: number | null;
  /**
   * Set by FrogBot to the user who created the record; read-only
   */
  createdBy?: (number | null) | User;
  /**
   * Set by FrogBot to the user who last saved the record; read-only
   */
  lastModifiedBy?: (number | null) | User;
  project?: (number | null) | Project;
  tags?: (number | Tag)[] | null;
  projectBudget?: number | null;
  projectStatus?: ('active' | 'paused') | null;
  tagNames?: string[] | null;
  notes?: string | null;
  /**
   * Generated automatically by AI from: notes. Writing a value keeps it and stops automatic updates
   */
  summary?: string | null;
  /**
   * Set by FrogBot: pending, done, error or manual. Write "pending" to regenerate the value
   */
  _summary_status?: ('pending' | 'done' | 'error' | 'manual') | null;
  /**
   * Set by FrogBot: the error message from the last failed run
   */
  _summary_error?: string | null;
  _order_board?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  budget?: number | null;
  status?: ('active' | 'paused') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timesheets".
 */
export interface Timesheet {
  id: number;
  title: string;
  /**
   * Duration in whole seconds, for example 5400 for 1 hour 30 minutes
   */
  logged?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  name: string;
  owner: number | User;
  prefix: string;
  tokenHash: string;
  lastUsedAt?: string | null;
  revokedAt?: string | null;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  totalCostUSD?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs".
 */
export interface UsageLog {
  id: number;
  apiKey?: (number | null) | ApiKey;
  user?: (number | null) | User;
  chat?: (number | null) | Chat;
  requestId: string;
  runId?: string | null;
  model: string;
  operation:
    | 'chat.completions'
    | 'messages'
    | 'responses'
    | 'embeddings'
    | 'images'
    | 'speech'
    | 'transcriptions'
    | 'videos'
    | 'rerank'
    | 'evaluate';
  inputTokens: number;
  outputTokens: number;
  cachedInputTokens?: number | null;
  cacheWriteTokens?: number | null;
  reasoningTokens?: number | null;
  totalTokens: number;
  /**
   * Decimal amount in USD, in whole units, not minor units such as cents
   */
  costUSD: number;
  finishReason?: string | null;
  requestedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-assets".
 */
export interface FrogBotChatAsset {
  id: number;
  owner?: (number | null) | User;
  chat?: (number | null) | Chat;
  sha256?: string | null;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-turns".
 */
export interface FrogBotChatTurn {
  id: string;
  state: 'idle' | 'running' | 'awaiting';
  attempt?: string | null;
  leaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints".
 */
export interface FrogBotWaitpoint {
  id: number;
  jobId: string;
  holder?: (number | null) | null;
  name: string;
  token: string;
  kind: 'delay' | 'resumable';
  ready: boolean;
  status: 'pending' | 'resumed' | 'expired';
  expiresAt?: string | null;
  until?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dispatched: boolean;
  dispatchOwner?: string | null;
  dispatchLeaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-autonumbers".
 */
export interface FrogBotAutonumber {
  id: number;
  key: string;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  modelAccess?: boolean;
  models?: boolean;
  monthlyBudget?: boolean;
  spendThisPeriodUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  resetPasswordRequestedAt?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect {
  id?: boolean;
  chat?: boolean;
  role?: boolean;
  parts?: boolean;
  metadata?: boolean;
  status?: boolean;
  delivery?: boolean;
  model?: boolean;
  reasoning?: boolean;
  author?: boolean;
  settlements?: boolean;
  version?: boolean;
  usage?:
    | boolean
    | {
        inputTokens?: boolean;
        outputTokens?: boolean;
        totalTokens?: boolean;
        reasoningTokens?: boolean;
        cachedInputTokens?: boolean;
        model?: boolean;
        provider?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect {
  _order?: boolean;
  title?: boolean;
  status?: boolean;
  channel?: boolean;
  dueAt?: boolean;
  labels?: boolean;
  progress?: boolean;
  score?: boolean;
  timeSpent?: boolean;
  website?: boolean;
  phone?: boolean;
  sku?: boolean;
  number?: boolean;
  createdBy?: boolean;
  lastModifiedBy?: boolean;
  project?: boolean;
  tags?: boolean;
  projectBudget?: boolean;
  projectStatus?: boolean;
  tagNames?: boolean;
  notes?: boolean;
  summary?: boolean;
  _summary_status?: boolean;
  _summary_error?: boolean;
  _order_board?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect {
  name?: boolean;
  budget?: boolean;
  status?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect {
  name?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timesheets_select".
 */
export interface TimesheetsSelect {
  title?: boolean;
  logged?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect {
  name?: boolean;
  owner?: boolean;
  prefix?: boolean;
  tokenHash?: boolean;
  lastUsedAt?: boolean;
  revokedAt?: boolean;
  totalCostUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs_select".
 */
export interface UsageLogsSelect {
  apiKey?: boolean;
  user?: boolean;
  chat?: boolean;
  requestId?: boolean;
  runId?: boolean;
  model?: boolean;
  operation?: boolean;
  inputTokens?: boolean;
  outputTokens?: boolean;
  cachedInputTokens?: boolean;
  cacheWriteTokens?: boolean;
  reasoningTokens?: boolean;
  totalTokens?: boolean;
  costUSD?: boolean;
  finishReason?: boolean;
  requestedAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats_select".
 */
export interface ChatsSelect {
  title?: boolean;
  user?: boolean;
  agent?: boolean;
  channel?: boolean;
  externalId?: boolean;
  channelKey?: boolean;
  channelThread?: boolean;
  channelLabel?: boolean;
  lastMessageAt?: boolean;
  todos?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-assets_select".
 */
export interface FrogBotChatAssetsSelect {
  owner?: boolean;
  chat?: boolean;
  sha256?: boolean;
  text?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-turns_select".
 */
export interface FrogBotChatTurnsSelect {
  id?: boolean;
  state?: boolean;
  attempt?: boolean;
  leaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints_select".
 */
export interface FrogBotWaitpointsSelect {
  jobId?: boolean;
  holder?: boolean;
  name?: boolean;
  token?: boolean;
  kind?: boolean;
  ready?: boolean;
  status?: boolean;
  expiresAt?: boolean;
  until?: boolean;
  data?: boolean;
  dispatched?: boolean;
  dispatchOwner?: boolean;
  dispatchLeaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-autonumbers_select".
 */
export interface FrogBotAutonumbersSelect {
  key?: boolean;
  value?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotResetAiBudgets".
 */
export interface TaskFrogBotResetAiBudgets {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotSweepJobs".
 */
export interface TaskFrogBotSweepJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotCleanupKv".
 */
export interface TaskFrogBotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotRunAIField".
 */
export interface TaskFrogBotRunAIField {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {
      questioner: unknown;
      picker: unknown;
    };
    models:
      | 'bedrock/amazon.nova-lite-v1:0'
      | 'bedrock/amazon.nova-micro-v1:0'
      | 'bedrock/amazon.nova-pro-v1:0'
      | 'bedrock/anthropic.claude-fable-5'
      | 'bedrock/anthropic.claude-fable-5-1'
      | 'bedrock/anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/anthropic.claude-opus-4-5-20251101-v1:0'
      | 'bedrock/anthropic.claude-opus-4-6-v1'
      | 'bedrock/anthropic.claude-opus-4-7'
      | 'bedrock/anthropic.claude-opus-4-8'
      | 'bedrock/anthropic.claude-opus-5'
      | 'bedrock/anthropic.claude-opus-5-5'
      | 'bedrock/anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/anthropic.claude-sonnet-4-6'
      | 'bedrock/anthropic.claude-sonnet-5'
      | 'bedrock/anthropic.claude-sonnet-5-5'
      | 'bedrock/apac.amazon.nova-lite-v1:0'
      | 'bedrock/apac.amazon.nova-micro-v1:0'
      | 'bedrock/apac.amazon.nova-pro-v1:0'
      | 'bedrock/au.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/au.anthropic.claude-opus-4-6-v1'
      | 'bedrock/au.anthropic.claude-opus-4-7'
      | 'bedrock/au.anthropic.claude-opus-4-8'
      | 'bedrock/au.anthropic.claude-opus-5'
      | 'bedrock/au.anthropic.claude-opus-5-5'
      | 'bedrock/au.anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/au.anthropic.claude-sonnet-4-6'
      | 'bedrock/au.anthropic.claude-sonnet-5'
      | 'bedrock/ca.amazon.nova-lite-v1:0'
      | 'bedrock/deepseek.r1-v1:0'
      | 'bedrock/deepseek.v3-v1:0'
      | 'bedrock/deepseek.v3.2'
      | 'bedrock/eu.amazon.nova-2-lite-v1:0'
      | 'bedrock/eu.amazon.nova-lite-v1:0'
      | 'bedrock/eu.amazon.nova-micro-v1:0'
      | 'bedrock/eu.amazon.nova-pro-v1:0'
      | 'bedrock/eu.anthropic.claude-fable-5'
      | 'bedrock/eu.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/eu.anthropic.claude-opus-4-5-20251101-v1:0'
      | 'bedrock/eu.anthropic.claude-opus-4-6-v1'
      | 'bedrock/eu.anthropic.claude-opus-4-7'
      | 'bedrock/eu.anthropic.claude-opus-4-8'
      | 'bedrock/eu.anthropic.claude-opus-5'
      | 'bedrock/eu.anthropic.claude-opus-5-5'
      | 'bedrock/eu.anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/eu.anthropic.claude-sonnet-4-6'
      | 'bedrock/eu.anthropic.claude-sonnet-5'
      | 'bedrock/eu.anthropic.claude-sonnet-5-5'
      | 'bedrock/eu.mistral.pixtral-large-2502-v1:0'
      | 'bedrock/global.amazon.nova-2-lite-v1:0'
      | 'bedrock/global.anthropic.claude-fable-5'
      | 'bedrock/global.anthropic.claude-fable-5-1'
      | 'bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/global.anthropic.claude-opus-4-5-20251101-v1:0'
      | 'bedrock/global.anthropic.claude-opus-4-6-v1'
      | 'bedrock/global.anthropic.claude-opus-4-7'
      | 'bedrock/global.anthropic.claude-opus-4-8'
      | 'bedrock/global.anthropic.claude-opus-5'
      | 'bedrock/global.anthropic.claude-opus-5-5'
      | 'bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/global.anthropic.claude-sonnet-4-6'
      | 'bedrock/global.anthropic.claude-sonnet-5'
      | 'bedrock/global.anthropic.claude-sonnet-5-5'
      | 'bedrock/global.moonshotai.kimi-k3'
      | 'bedrock/global.openai.gpt-5.6-luna'
      | 'bedrock/global.openai.gpt-5.6-sol'
      | 'bedrock/global.openai.gpt-5.6-terra'
      | 'bedrock/global.openai.gpt-6-astra'
      | 'bedrock/global.openai.gpt-6-luna'
      | 'bedrock/global.openai.gpt-6-sol'
      | 'bedrock/global.openai.gpt-6.1-sol'
      | 'bedrock/global.xai.grok-4.6'
      | 'bedrock/global.xai.grok-4.7'
      | 'bedrock/google.gemma-3-12b-it'
      | 'bedrock/google.gemma-3-27b-it'
      | 'bedrock/google.gemma-3-4b-it'
      | 'bedrock/google.gemma-4-26b-a4b'
      | 'bedrock/google.gemma-4-31b'
      | 'bedrock/google.gemma-4-e2b'
      | 'bedrock/in.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/in.anthropic.claude-opus-5'
      | 'bedrock/in.anthropic.claude-sonnet-5'
      | 'bedrock/in.openai.gpt-5.6-luna'
      | 'bedrock/in.openai.gpt-5.6-terra'
      | 'bedrock/jp.amazon.nova-2-lite-v1:0'
      | 'bedrock/jp.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/jp.anthropic.claude-opus-4-7'
      | 'bedrock/jp.anthropic.claude-opus-4-8'
      | 'bedrock/jp.anthropic.claude-opus-5'
      | 'bedrock/jp.anthropic.claude-opus-5-5'
      | 'bedrock/jp.anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/jp.anthropic.claude-sonnet-4-6'
      | 'bedrock/jp.anthropic.claude-sonnet-5'
      | 'bedrock/meta.llama3-1-70b-instruct-v1:0'
      | 'bedrock/meta.llama4-maverick-17b-instruct-v1:0'
      | 'bedrock/meta.llama4-scout-17b-instruct-v1:0'
      | 'bedrock/minimax.minimax-m2'
      | 'bedrock/minimax.minimax-m2.1'
      | 'bedrock/minimax.minimax-m2.5'
      | 'bedrock/mistral.devstral-2-123b'
      | 'bedrock/mistral.magistral-small-2509'
      | 'bedrock/mistral.ministral-3-14b-instruct'
      | 'bedrock/mistral.ministral-3-3b-instruct'
      | 'bedrock/mistral.ministral-3-8b-instruct'
      | 'bedrock/mistral.mistral-large-3-675b-instruct'
      | 'bedrock/mistral.pixtral-large-2502-v1:0'
      | 'bedrock/mistral.voxtral-mini-3b-2507'
      | 'bedrock/mistral.voxtral-small-24b-2507'
      | 'bedrock/moonshot.kimi-k2-thinking'
      | 'bedrock/moonshotai.kimi-k2.5'
      | 'bedrock/nvidia.nemotron-nano-12b-v2'
      | 'bedrock/nvidia.nemotron-nano-3-30b'
      | 'bedrock/nvidia.nemotron-nano-9b-v2'
      | 'bedrock/nvidia.nemotron-super-3-120b'
      | 'bedrock/openai.gpt-5.4'
      | 'bedrock/openai.gpt-5.5'
      | 'bedrock/openai.gpt-5.6-luna'
      | 'bedrock/openai.gpt-5.6-sol'
      | 'bedrock/openai.gpt-5.6-terra'
      | 'bedrock/openai.gpt-6-astra'
      | 'bedrock/openai.gpt-6-luna'
      | 'bedrock/openai.gpt-6-sol'
      | 'bedrock/openai.gpt-6.1-sol'
      | 'bedrock/openai.gpt-oss-120b'
      | 'bedrock/openai.gpt-oss-120b-1:0'
      | 'bedrock/openai.gpt-oss-20b'
      | 'bedrock/openai.gpt-oss-20b-1:0'
      | 'bedrock/openai.gpt-oss-safeguard-120b'
      | 'bedrock/openai.gpt-oss-safeguard-20b'
      | 'bedrock/qwen.qwen3-235b-a22b-2507-v1:0'
      | 'bedrock/qwen.qwen3-32b-v1:0'
      | 'bedrock/qwen.qwen3-coder-30b-a3b-v1:0'
      | 'bedrock/qwen.qwen3-coder-480b-a35b-v1:0'
      | 'bedrock/qwen.qwen3-coder-next'
      | 'bedrock/qwen.qwen3-next-80b-a3b'
      | 'bedrock/qwen.qwen3-vl-235b-a22b'
      | 'bedrock/us-gov.openai.gpt-oss-120b-1:0'
      | 'bedrock/us-gov.openai.gpt-oss-20b-1:0'
      | 'bedrock/us.amazon.nova-2-lite-v1:0'
      | 'bedrock/us.amazon.nova-lite-v1:0'
      | 'bedrock/us.amazon.nova-micro-v1:0'
      | 'bedrock/us.amazon.nova-pro-v1:0'
      | 'bedrock/us.anthropic.claude-fable-5'
      | 'bedrock/us.anthropic.claude-fable-5-1'
      | 'bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0'
      | 'bedrock/us.anthropic.claude-opus-4-5-20251101-v1:0'
      | 'bedrock/us.anthropic.claude-opus-4-6-v1'
      | 'bedrock/us.anthropic.claude-opus-4-7'
      | 'bedrock/us.anthropic.claude-opus-4-8'
      | 'bedrock/us.anthropic.claude-opus-5'
      | 'bedrock/us.anthropic.claude-opus-5-5'
      | 'bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0'
      | 'bedrock/us.anthropic.claude-sonnet-4-6'
      | 'bedrock/us.anthropic.claude-sonnet-5'
      | 'bedrock/us.anthropic.claude-sonnet-5-5'
      | 'bedrock/us.deepseek.r1-v1:0'
      | 'bedrock/us.meta.llama3-1-70b-instruct-v1:0'
      | 'bedrock/us.meta.llama3-1-8b-instruct-v1:0'
      | 'bedrock/us.meta.llama3-3-70b-instruct-v1:0'
      | 'bedrock/us.meta.llama4-maverick-17b-instruct-v1:0'
      | 'bedrock/us.meta.llama4-scout-17b-instruct-v1:0'
      | 'bedrock/us.mistral.pixtral-large-2502-v1:0'
      | 'bedrock/us.moonshotai.kimi-k3'
      | 'bedrock/us.openai.gpt-5.6-luna'
      | 'bedrock/us.openai.gpt-5.6-sol'
      | 'bedrock/us.openai.gpt-5.6-terra'
      | 'bedrock/us.openai.gpt-6-astra'
      | 'bedrock/us.openai.gpt-6-luna'
      | 'bedrock/us.openai.gpt-6-sol'
      | 'bedrock/us.openai.gpt-6.1-sol'
      | 'bedrock/us.writer.palmyra-x4-v1:0'
      | 'bedrock/us.writer.palmyra-x5-v1:0'
      | 'bedrock/us.xai.grok-4.6'
      | 'bedrock/us.xai.grok-4.7'
      | 'bedrock/writer.palmyra-x4-v1:0'
      | 'bedrock/writer.palmyra-x5-v1:0'
      | 'bedrock/xai.grok-4.3'
      | 'bedrock/xai.grok-4.6'
      | 'bedrock/zai.glm-4.7'
      | 'bedrock/zai.glm-4.7-flash'
      | 'bedrock/zai.glm-5'
      | 'browser/deliberator'
      | 'browser/questioner'
      | 'browser/sprinter'
      | 'browser/thinker'
      | 'browser/verbose'
      | 'openrouter/aion-labs/aion-2.0'
      | 'openrouter/aion-labs/aion-3.0'
      | 'openrouter/aion-labs/aion-3.0-mini'
      | 'openrouter/aion-labs/aion-3.5'
      | 'openrouter/aion-labs/aion-3.5-mini'
      | 'openrouter/aion-labs/aion-rp-llama-3.1-8b'
      | 'openrouter/amazon/nova-2-lite-v1'
      | 'openrouter/amazon/nova-lite-v1'
      | 'openrouter/amazon/nova-micro-v1'
      | 'openrouter/amazon/nova-premier-v1'
      | 'openrouter/amazon/nova-pro-v1'
      | 'openrouter/anthracite-org/magnum-v4-72b'
      | 'openrouter/anthropic/claude-fable-5'
      | 'openrouter/anthropic/claude-fable-5.1'
      | 'openrouter/anthropic/claude-haiku-4.5'
      | 'openrouter/anthropic/claude-opus-4.1'
      | 'openrouter/anthropic/claude-opus-4.5'
      | 'openrouter/anthropic/claude-opus-4.6'
      | 'openrouter/anthropic/claude-opus-4.7'
      | 'openrouter/anthropic/claude-opus-4.8'
      | 'openrouter/anthropic/claude-opus-5'
      | 'openrouter/anthropic/claude-opus-5.5'
      | 'openrouter/anthropic/claude-sonnet-4'
      | 'openrouter/anthropic/claude-sonnet-4.5'
      | 'openrouter/anthropic/claude-sonnet-4.6'
      | 'openrouter/anthropic/claude-sonnet-5'
      | 'openrouter/anthropic/claude-sonnet-5.5'
      | 'openrouter/apodex/apodex-1.1-mini:free'
      | 'openrouter/arcee-ai/trinity-large-thinking'
      | 'openrouter/baidu/ernie-4.5-vl-424b-a47b'
      | 'openrouter/bytedance-seed/seed-1.6'
      | 'openrouter/bytedance-seed/seed-1.6-flash'
      | 'openrouter/bytedance-seed/seed-2-1-turbo'
      | 'openrouter/bytedance-seed/seed-2.0-code'
      | 'openrouter/bytedance-seed/seed-2.0-lite'
      | 'openrouter/bytedance-seed/seed-2.0-mini'
      | 'openrouter/bytedance/ui-tars-1.5-7b'
      | 'openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition'
      | 'openrouter/cohere/command-a'
      | 'openrouter/cohere/command-a-plus'
      | 'openrouter/cohere/command-r-08-2024'
      | 'openrouter/cohere/command-r-plus-08-2024'
      | 'openrouter/cohere/command-r7b-12-2024'
      | 'openrouter/cohere/north-mini-code:free'
      | 'openrouter/deepseek/deepseek-chat'
      | 'openrouter/deepseek/deepseek-chat-v3-0324'
      | 'openrouter/deepseek/deepseek-chat-v3.1'
      | 'openrouter/deepseek/deepseek-r1'
      | 'openrouter/deepseek/deepseek-r1-0528'
      | 'openrouter/deepseek/deepseek-v3.1-terminus'
      | 'openrouter/deepseek/deepseek-v3.2'
      | 'openrouter/deepseek/deepseek-v3.2-exp'
      | 'openrouter/deepseek/deepseek-v4-flash'
      | 'openrouter/deepseek/deepseek-v4-flash-0731'
      | 'openrouter/deepseek/deepseek-v4-flash-vision-exp'
      | 'openrouter/deepseek/deepseek-v4-pro'
      | 'openrouter/deepseek/deepseek-v4-pro-0813'
      | 'openrouter/deepseek/deepseek-v4.1-flash'
      | 'openrouter/dots-studio/dots-3-note-preview:free'
      | 'openrouter/fireworks/ember-1'
      | 'openrouter/google/gemini-2.5-flash'
      | 'openrouter/google/gemini-2.5-flash-lite'
      | 'openrouter/google/gemini-2.5-pro'
      | 'openrouter/google/gemini-2.5-pro-preview'
      | 'openrouter/google/gemini-3-flash-preview'
      | 'openrouter/google/gemini-3.1-flash-lite'
      | 'openrouter/google/gemini-3.1-flash-lite-preview'
      | 'openrouter/google/gemini-3.1-pro-preview'
      | 'openrouter/google/gemini-3.1-pro-preview-customtools'
      | 'openrouter/google/gemini-3.5-flash'
      | 'openrouter/google/gemini-3.5-flash-lite'
      | 'openrouter/google/gemini-3.6-flash'
      | 'openrouter/google/gemini-3.7-flash'
      | 'openrouter/google/gemini-3.8-flash'
      | 'openrouter/google/gemma-2-27b-it'
      | 'openrouter/google/gemma-3-12b-it'
      | 'openrouter/google/gemma-3-27b-it'
      | 'openrouter/google/gemma-3-4b-it'
      | 'openrouter/google/gemma-4-26b-a4b-it'
      | 'openrouter/google/gemma-4-26b-a4b-it:free'
      | 'openrouter/google/gemma-4-31b-it'
      | 'openrouter/google/gemma-4-31b-it:free'
      | 'openrouter/gryphe/mythomax-l2-13b'
      | 'openrouter/ibm-granite/granite-4.0-h-micro'
      | 'openrouter/ibm-granite/granite-4.2-8b'
      | 'openrouter/inception/mercury-2'
      | 'openrouter/inception/mercury-2.5'
      | 'openrouter/inclusionai/ling-3.0-flash'
      | 'openrouter/inclusionai/ling-3.0-flash-fin'
      | 'openrouter/inclusionai/ling-3.0-flash-sante:free'
      | 'openrouter/inclusionai/ling-3.0-flash-vl'
      | 'openrouter/inclusionai/ling-3.1-flash'
      | 'openrouter/inference-net/schematron-v2-small'
      | 'openrouter/inference-net/schematron-v2-turbo'
      | 'openrouter/kwaipilot/kat-coder-pro-v2.5'
      | 'openrouter/liquid/lfm-2.5-2.6b:free'
      | 'openrouter/mancer/weaver'
      | 'openrouter/meituan/longcat-2.0'
      | 'openrouter/meta-llama/llama-3.1-70b-instruct'
      | 'openrouter/meta-llama/llama-3.1-8b-instruct'
      | 'openrouter/meta-llama/llama-3.2-1b-instruct'
      | 'openrouter/meta-llama/llama-3.2-3b-instruct'
      | 'openrouter/meta-llama/llama-3.3-70b-instruct'
      | 'openrouter/meta-llama/llama-4-maverick'
      | 'openrouter/meta-llama/llama-4-scout'
      | 'openrouter/meta-llama/llama-guard-4-12b'
      | 'openrouter/meta/muse-glimmer-30b'
      | 'openrouter/meta/muse-spark-1.1'
      | 'openrouter/meta/muse-spark-1.2'
      | 'openrouter/meta/muse-spark-1.2-contributor'
      | 'openrouter/meta/muse-spark-1.3'
      | 'openrouter/meta/muse-spark-1.3-contributor'
      | 'openrouter/microsoft/phi-4'
      | 'openrouter/microsoft/wizardlm-2-8x22b'
      | 'openrouter/minimax/minimax-01'
      | 'openrouter/minimax/minimax-m1'
      | 'openrouter/minimax/minimax-m2'
      | 'openrouter/minimax/minimax-m2-her'
      | 'openrouter/minimax/minimax-m2.1'
      | 'openrouter/minimax/minimax-m2.5'
      | 'openrouter/minimax/minimax-m2.7'
      | 'openrouter/minimax/minimax-m3'
      | 'openrouter/mistralai/codestral-2508'
      | 'openrouter/mistralai/devstral-2512'
      | 'openrouter/mistralai/ministral-14b-2512'
      | 'openrouter/mistralai/ministral-3b-2512'
      | 'openrouter/mistralai/ministral-8b-2512'
      | 'openrouter/mistralai/mistral-large'
      | 'openrouter/mistralai/mistral-large-2407'
      | 'openrouter/mistralai/mistral-large-2512'
      | 'openrouter/mistralai/mistral-medium-3'
      | 'openrouter/mistralai/mistral-medium-3-5'
      | 'openrouter/mistralai/mistral-medium-3.1'
      | 'openrouter/mistralai/mistral-nemo'
      | 'openrouter/mistralai/mistral-saba'
      | 'openrouter/mistralai/mistral-small-24b-instruct-2501'
      | 'openrouter/mistralai/mistral-small-2603'
      | 'openrouter/mistralai/mistral-small-3.1-24b-instruct'
      | 'openrouter/mistralai/mistral-small-3.2-24b-instruct'
      | 'openrouter/mistralai/mixtral-8x22b-instruct'
      | 'openrouter/mistralai/voxtral-small-24b-2507'
      | 'openrouter/moonshotai/kimi-k2'
      | 'openrouter/moonshotai/kimi-k2-0905'
      | 'openrouter/moonshotai/kimi-k2-thinking'
      | 'openrouter/moonshotai/kimi-k2.5'
      | 'openrouter/moonshotai/kimi-k2.6'
      | 'openrouter/moonshotai/kimi-k2.7-code'
      | 'openrouter/moonshotai/kimi-k3'
      | 'openrouter/morph/morph-v3-fast'
      | 'openrouter/morph/morph-v3-large'
      | 'openrouter/nex-agi/nex-n2.5-mini'
      | 'openrouter/nex-agi/nex-n2.5-pro'
      | 'openrouter/nousresearch/hermes-3-llama-3.1-405b'
      | 'openrouter/nousresearch/hermes-3-llama-3.1-70b'
      | 'openrouter/nousresearch/hermes-4-405b'
      | 'openrouter/nvidia/nemotron-3-nano-30b-a3b'
      | 'openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free'
      | 'openrouter/nvidia/nemotron-3-super-120b-a12b'
      | 'openrouter/nvidia/nemotron-3-super-120b-a12b:free'
      | 'openrouter/nvidia/nemotron-3-ultra-550b-a55b'
      | 'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free'
      | 'openrouter/nvidia/nemotron-3.5-content-safety'
      | 'openrouter/nvidia/nemotron-3.5-content-safety:free'
      | 'openrouter/nvidia/nemotron-3.5-lightning'
      | 'openrouter/nvidia/nemotron-3.5-lightning:free'
      | 'openrouter/openai/gpt-3.5-turbo'
      | 'openrouter/openai/gpt-3.5-turbo-0613'
      | 'openrouter/openai/gpt-3.5-turbo-16k'
      | 'openrouter/openai/gpt-3.5-turbo-instruct'
      | 'openrouter/openai/gpt-4'
      | 'openrouter/openai/gpt-4-turbo'
      | 'openrouter/openai/gpt-4.1'
      | 'openrouter/openai/gpt-4.1-mini'
      | 'openrouter/openai/gpt-4.1-nano'
      | 'openrouter/openai/gpt-4o'
      | 'openrouter/openai/gpt-4o-2024-05-13'
      | 'openrouter/openai/gpt-4o-2024-08-06'
      | 'openrouter/openai/gpt-4o-2024-11-20'
      | 'openrouter/openai/gpt-4o-mini'
      | 'openrouter/openai/gpt-4o-mini-2024-07-18'
      | 'openrouter/openai/gpt-5'
      | 'openrouter/openai/gpt-5-mini'
      | 'openrouter/openai/gpt-5-nano'
      | 'openrouter/openai/gpt-5-pro'
      | 'openrouter/openai/gpt-5.1'
      | 'openrouter/openai/gpt-5.1-codex'
      | 'openrouter/openai/gpt-5.1-codex-max'
      | 'openrouter/openai/gpt-5.1-codex-mini'
      | 'openrouter/openai/gpt-5.2'
      | 'openrouter/openai/gpt-5.2-chat'
      | 'openrouter/openai/gpt-5.2-codex'
      | 'openrouter/openai/gpt-5.2-pro'
      | 'openrouter/openai/gpt-5.3-codex'
      | 'openrouter/openai/gpt-5.4'
      | 'openrouter/openai/gpt-5.4-mini'
      | 'openrouter/openai/gpt-5.4-nano'
      | 'openrouter/openai/gpt-5.4-pro'
      | 'openrouter/openai/gpt-5.5'
      | 'openrouter/openai/gpt-5.5-pro'
      | 'openrouter/openai/gpt-5.6-luna'
      | 'openrouter/openai/gpt-5.6-luna-pro'
      | 'openrouter/openai/gpt-5.6-sol'
      | 'openrouter/openai/gpt-5.6-sol-pro'
      | 'openrouter/openai/gpt-5.6-terra'
      | 'openrouter/openai/gpt-5.6-terra-pro'
      | 'openrouter/openai/gpt-6-astra'
      | 'openrouter/openai/gpt-6-astra-pro'
      | 'openrouter/openai/gpt-6-luna'
      | 'openrouter/openai/gpt-6-luna-pro'
      | 'openrouter/openai/gpt-6-sol'
      | 'openrouter/openai/gpt-6-sol-pro'
      | 'openrouter/openai/gpt-6.1-sol'
      | 'openrouter/openai/gpt-6.1-sol-pro'
      | 'openrouter/openai/gpt-chat-latest'
      | 'openrouter/openai/gpt-oss-120b'
      | 'openrouter/openai/gpt-oss-20b'
      | 'openrouter/openai/gpt-oss-safeguard-20b'
      | 'openrouter/openai/o1'
      | 'openrouter/openai/o1-pro'
      | 'openrouter/openai/o3'
      | 'openrouter/openai/o3-mini'
      | 'openrouter/openai/o3-mini-high'
      | 'openrouter/openai/o3-pro'
      | 'openrouter/openai/o4-mini'
      | 'openrouter/openai/o4-mini-high'
      | 'openrouter/openrouter/free'
      | 'openrouter/perceptron/perceptron-mk1'
      | 'openrouter/perceptron/perceptron-mk1.5'
      | 'openrouter/perplexity/sonar'
      | 'openrouter/perplexity/sonar-deep-research'
      | 'openrouter/perplexity/sonar-pro'
      | 'openrouter/perplexity/sonar-pro-search'
      | 'openrouter/perplexity/sonar-reasoning-pro'
      | 'openrouter/poolside/laguna-s-2.1'
      | 'openrouter/poolside/laguna-s-2.1:free'
      | 'openrouter/poolside/laguna-xs-2.1'
      | 'openrouter/poolside/laguna-xs-2.1:free'
      | 'openrouter/prism-ml/ternary-bonsai-2-27b'
      | 'openrouter/qwen/qwen-2.5-72b-instruct'
      | 'openrouter/qwen/qwen-2.5-7b-instruct'
      | 'openrouter/qwen/qwen-2.5-coder-32b-instruct'
      | 'openrouter/qwen/qwen-plus'
      | 'openrouter/qwen/qwen-plus-2025-07-28'
      | 'openrouter/qwen/qwen2.5-vl-72b-instruct'
      | 'openrouter/qwen/qwen3-14b'
      | 'openrouter/qwen/qwen3-235b-a22b'
      | 'openrouter/qwen/qwen3-235b-a22b-2507'
      | 'openrouter/qwen/qwen3-235b-a22b-thinking-2507'
      | 'openrouter/qwen/qwen3-30b-a3b'
      | 'openrouter/qwen/qwen3-30b-a3b-instruct-2507'
      | 'openrouter/qwen/qwen3-30b-a3b-thinking-2507'
      | 'openrouter/qwen/qwen3-32b'
      | 'openrouter/qwen/qwen3-8b'
      | 'openrouter/qwen/qwen3-coder'
      | 'openrouter/qwen/qwen3-coder-30b-a3b-instruct'
      | 'openrouter/qwen/qwen3-coder-flash'
      | 'openrouter/qwen/qwen3-coder-next'
      | 'openrouter/qwen/qwen3-coder-plus'
      | 'openrouter/qwen/qwen3-max'
      | 'openrouter/qwen/qwen3-max-thinking'
      | 'openrouter/qwen/qwen3-next-80b-a3b-instruct'
      | 'openrouter/qwen/qwen3-next-80b-a3b-thinking'
      | 'openrouter/qwen/qwen3-vl-235b-a22b-instruct'
      | 'openrouter/qwen/qwen3-vl-235b-a22b-thinking'
      | 'openrouter/qwen/qwen3-vl-30b-a3b-instruct'
      | 'openrouter/qwen/qwen3-vl-30b-a3b-thinking'
      | 'openrouter/qwen/qwen3-vl-32b-instruct'
      | 'openrouter/qwen/qwen3-vl-8b-instruct'
      | 'openrouter/qwen/qwen3-vl-8b-thinking'
      | 'openrouter/qwen/qwen3.5-122b-a10b'
      | 'openrouter/qwen/qwen3.5-27b'
      | 'openrouter/qwen/qwen3.5-35b-a3b'
      | 'openrouter/qwen/qwen3.5-397b-a17b'
      | 'openrouter/qwen/qwen3.5-9b'
      | 'openrouter/qwen/qwen3.5-flash-02-23'
      | 'openrouter/qwen/qwen3.5-plus-02-15'
      | 'openrouter/qwen/qwen3.5-plus-20260420'
      | 'openrouter/qwen/qwen3.6-27b'
      | 'openrouter/qwen/qwen3.6-35b-a3b'
      | 'openrouter/qwen/qwen3.6-flash'
      | 'openrouter/qwen/qwen3.6-max-preview'
      | 'openrouter/qwen/qwen3.6-plus'
      | 'openrouter/qwen/qwen3.7-flash'
      | 'openrouter/qwen/qwen3.7-max'
      | 'openrouter/qwen/qwen3.7-plus'
      | 'openrouter/qwen/qwen3.8-2.4t-a95b'
      | 'openrouter/qwen/qwen3.8-27b'
      | 'openrouter/qwen/qwen3.8-27b:free'
      | 'openrouter/qwen/qwen3.8-flash'
      | 'openrouter/qwen/qwen3.8-max-0902'
      | 'openrouter/qwen/qwen3.8-max-prime'
      | 'openrouter/qwen/qwen3.8-omni-flash'
      | 'openrouter/rekaai/reka-edge'
      | 'openrouter/rekaai/reka-flash-3'
      | 'openrouter/relace/relace-apply-3'
      | 'openrouter/relace/relace-search'
      | 'openrouter/sakana/fugu-max'
      | 'openrouter/sakana/fugu-ultra'
      | 'openrouter/sakana/fugu-ultra-v2'
      | 'openrouter/sakana/sakana-namazu'
      | 'openrouter/sao10k/l3-lunaris-8b'
      | 'openrouter/sao10k/l3.1-euryale-70b'
      | 'openrouter/sao10k/l3.3-euryale-70b'
      | 'openrouter/stealth/space-bunny-alpha'
      | 'openrouter/stepfun/step-3.5-flash'
      | 'openrouter/stepfun/step-3.7-flash'
      | 'openrouter/tencent/hunyuan-a13b-instruct'
      | 'openrouter/tencent/hy-mt2-1.8b'
      | 'openrouter/tencent/hy-mt2-30b-a3b'
      | 'openrouter/tencent/hy-mt2-7b'
      | 'openrouter/tencent/hy3'
      | 'openrouter/tencent/hy3-preview'
      | 'openrouter/tencent/hy4-preview'
      | 'openrouter/thedrummer/cydonia-24b-v4.1'
      | 'openrouter/thedrummer/skyfall-36b-v2'
      | 'openrouter/thedrummer/unslopnemo-12b'
      | 'openrouter/thinkingmachines/inkling'
      | 'openrouter/thinkingmachines/inkling-small'
      | 'openrouter/thinkingmachines/inkling-small:free'
      | 'openrouter/thinkingmachines/inkling:free'
      | 'openrouter/unbiased/pareto'
      | 'openrouter/unbiased/pareto-26.10-preview'
      | 'openrouter/undi95/remm-slerp-l2-13b'
      | 'openrouter/upstage/solar-mini4'
      | 'openrouter/upstage/solar-pro-3'
      | 'openrouter/upstage/solar-pro4'
      | 'openrouter/writer/palmyra-x5'
      | 'openrouter/x-ai/grok-4.20'
      | 'openrouter/x-ai/grok-4.20-multi-agent'
      | 'openrouter/x-ai/grok-4.3'
      | 'openrouter/x-ai/grok-4.5'
      | 'openrouter/x-ai/grok-4.6'
      | 'openrouter/x-ai/grok-4.7'
      | 'openrouter/x-ai/grok-build-0.1'
      | 'openrouter/xiaomi/mimo-v2.5'
      | 'openrouter/xiaomi/mimo-v2.5-pro'
      | 'openrouter/xiaomi/mimo-v2.6-flash'
      | 'openrouter/xiaomi/mimo-v2.6-pro'
      | 'openrouter/xiaomi/mimo-v2.6-pro-ultraspeed'
      | 'openrouter/z-ai/glm-4.5'
      | 'openrouter/z-ai/glm-4.5-air'
      | 'openrouter/z-ai/glm-4.5v'
      | 'openrouter/z-ai/glm-4.6'
      | 'openrouter/z-ai/glm-4.6v'
      | 'openrouter/z-ai/glm-4.7'
      | 'openrouter/z-ai/glm-4.7-flash'
      | 'openrouter/z-ai/glm-5'
      | 'openrouter/z-ai/glm-5-turbo'
      | 'openrouter/z-ai/glm-5.1'
      | 'openrouter/z-ai/glm-5.2'
      | 'openrouter/z-ai/glm-5.3'
      | 'openrouter/z-ai/glm-5.3-flash'
      | 'openrouter/z-ai/glm-5.3-flashx'
      | 'openrouter/z-ai/glm-5.3-prime'
      | 'openrouter/z-ai/glm-5v-turbo'
      | 'openrouter/~anthropic/claude-fable-latest'
      | 'openrouter/~anthropic/claude-haiku-latest'
      | 'openrouter/~anthropic/claude-opus-latest'
      | 'openrouter/~anthropic/claude-sonnet-latest'
      | 'openrouter/~deepseek/deepseek-flash-latest'
      | 'openrouter/~deepseek/deepseek-pro-latest'
      | 'openrouter/~deepseek/deepseek-v4-flash-latest'
      | 'openrouter/~google/gemini-flash-latest'
      | 'openrouter/~google/gemini-pro-latest'
      | 'openrouter/~moonshotai/kimi-latest'
      | 'openrouter/~openai/gpt-astra-latest'
      | 'openrouter/~openai/gpt-luna-latest'
      | 'openrouter/~openai/gpt-mini-latest'
      | 'openrouter/~openai/gpt-sol-latest'
      | 'openrouter/~openai/gpt-terra-latest'
      | 'openrouter/~x-ai/grok-latest'
      | 'openrouter/~z-ai/glm-flash-latest'
      | 'openrouter/~z-ai/glm-latest';
    roles: never;
  }
}
