import rule from '../../../scripts/eslint-plugin/rules/no-comments.mjs';
import { file, ruleTester } from './ruleTester';

const filename = file('packages/frogbot/src/chat/example.ts');

const script = file('scripts/example.mjs');

ruleTester.run('no-comments', rule, {
  valid: [
    {
      name: 'JSDoc on exported declarations',
      code: [
        '/** A label. */',
        'export const label = 1;',
        '/** Echo. */',
        'export function echo(value: string) {',
        '  return value;',
        '}',
        '/** The default. */',
        'export default class Thing {}',
      ].join('\n'),
      filename,
    },
    {
      name: 'JSDoc on members of exported types, interfaces, classes and config objects',
      code: [
        'export type Options = {',
        '  /** The model. */',
        '  model: string;',
        '  nested: {',
        '    /** A nested option. */',
        '    depth: number;',
        '  };',
        '};',
        'export interface Plugin {',
        '  /** Runs first. */',
        '  init(): void;',
        '}',
        'export class Client {',
        '  /** The base URL. */',
        "  url = '';",
        '}',
        'export const defaults = {',
        '  /** Retries. */',
        '  retries: 2,',
        '};',
        'export function configure(options: {',
        '  /** Applies to every request. */',
        '  timeout: number;',
        '}) {',
        '  return options;',
        '}',
        'export enum Mode {',
        '  /** Fast. */',
        '  Fast,',
        '}',
      ].join('\n'),
      filename,
    },
    {
      name: 'JSDoc on a declaration exported by name later',
      code: [
        '/** Local. */',
        'type Local = { /** A field. */ a: string };',
        'export type { Local };',
      ].join('\n'),
      filename,
    },
    {
      name: 'JSDoc inside a module augmentation',
      code: [
        "declare module 'payload' {",
        '  /** Augmented. */',
        '  interface Config {',
        '    /** A FrogBot option. */',
        '    frogbot: boolean;',
        '  }',
        '}',
      ].join('\n'),
      filename,
    },
    {
      name: 'eslint and oxlint directives with a reason',
      code: [
        '/* eslint-disable no-console -- a CLI prints */',
        '// eslint-disable-next-line no-console -- a CLI prints',
        "console.log('x'); // eslint-disable-line no-console -- a CLI prints",
        '/* eslint-enable no-console */',
        '// oxlint-disable-next-line no-explicit-any -- the SDK is untyped',
        'export const value: any = 1;',
      ].join('\n'),
      filename,
    },
    {
      name: 'TypeScript, bundler, minifier, coverage and formatter directives',
      code: [
        '// @ts-expect-error the value is a string',
        'export const count: number = "1";',
        'export const load = (url: string) =>',
        '  import(/* webpackIgnore: true */ /* turbopackIgnore: true */ /* @vite-ignore */ url);',
        'export const pure = /* #__PURE__ */ make();',
        'export const alsoPure = /* @__PURE__ */ make();',
        '/* c8 ignore next */',
        'export const ignored = 1;',
        '// prettier-ignore',
        'export const grid = [1,0,',
        '                     0,1];',
      ].join('\n'),
      filename,
    },
    {
      name: 'triple-slash references and shebangs',
      code: ['#!/usr/bin/env node', '/// <reference lib="esnext.array" />', 'export {};'].join(
        '\n',
      ),
      filename: file('packages/frogbot/src/bin/example.ts'),
    },
    {
      name: 'an upstream workaround link that says when to remove it',
      code: [
        '// Workaround: https://github.com/payloadcms/payload/pull/18188, remove when Payload is past 3.90.2',
        'export const flag = true;',
      ].join('\n'),
      filename,
    },
    {
      name: 'JSDoc type annotations in JavaScript files',
      code: [
        "/** @type {import('eslint').Rule.RuleModule} */",
        'const rule = {};',
        '/**',
        ' * @param {string} value',
        ' * @returns {string}',
        ' */',
        'function echo(value) {',
        '  return value;',
        '}',
      ].join('\n'),
      filename: script,
    },
    {
      name: 'a ts-expect-error inside JSX',
      code: [
        'export const view = (',
        '  <div>',
        '    {/* @ts-expect-error Slot does not support asChild */}',
        '    <Slot asChild />',
        '  </div>',
        ');',
      ].join('\n'),
      filename: file('packages/ui/src/components/example.tsx'),
      languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    },
    {
      name: 'source map links and the check runner marker',
      code: [
        '#!/usr/bin/env node',
        '// check: full-only',
        'export const run = 1;',
        '//# sourceMappingURL=run.js.map',
      ].join('\n'),
      filename: file('scripts/check-example.mjs'),
    },
    {
      name: 'vendored folders are exempt',
      code: '// Copied from Payload.\nexport const vendored = 1;',
      filename: file('packages/sdk/src/example.ts'),
    },
  ],
  invalid: [
    {
      name: 'a whole-line comment and a run of them',
      code: [
        '// One.',
        'export const a = 1;',
        '',
        '  // Two',
        '  // lines.',
        'export const b = 2;',
      ].join('\n'),
      output: ['export const a = 1;', '', 'export const b = 2;'].join('\n'),
      filename,
      errors: [{ messageId: 'comment' }, { messageId: 'comment' }, { messageId: 'comment' }],
    },
    {
      name: 'a trailing comment and an inline block comment',
      code: ['export const a = 1; // trailing', 'export const b = /* inline */ 2;'].join('\n'),
      output: ['export const a = 1;', 'export const b = 2;'].join('\n'),
      filename,
      errors: [{ messageId: 'comment' }, { messageId: 'comment' }],
    },
    {
      name: 'a block comment between tokens keeps them apart',
      code: 'export const a = typeof/* x */b;',
      output: 'export const a = typeof b;',
      filename,
      errors: [{ messageId: 'comment' }],
    },
    {
      name: 'JSDoc on non-exported declarations and on statements inside exported functions',
      code: [
        '/** Private. */',
        'const hidden = 1;',
        'type Local = {',
        '  /** Private member. */',
        '  a: string;',
        '};',
        'export function make() {',
        '  /** Inside. */',
        '  return { /** Not an option. */ a: hidden };',
        '}',
        'export const build = () => ({',
        '  /** Returned, not configured. */',
        '  b: 1,',
        '});',
        '/** At the end. */',
      ].join('\n'),
      output: [
        'const hidden = 1;',
        'type Local = {',
        '  a: string;',
        '};',
        'export function make() {',
        '  return { a: hidden };',
        '}',
        'export const build = () => ({',
        '  b: 1,',
        '});',
      ].join('\n'),
      filename,
      errors: Array.from({ length: 6 }, () => ({ messageId: 'comment' })),
    },
    {
      name: 'JSDoc without type tags in JavaScript files',
      code: ['/** Runs the check. */', 'function check() {}', 'check();'].join('\n'),
      output: ['function check() {}', 'check();'].join('\n'),
      filename: script,
      errors: [{ messageId: 'comment' }],
    },
    {
      name: 'a JSX comment and its braces',
      code: [
        'export const view = (',
        '  <div>',
        '    {/* Explains the child. */}',
        '    <span />',
        '  </div>',
        ');',
      ].join('\n'),
      output: ['export const view = (', '  <div>', '    <span />', '  </div>', ');'].join('\n'),
      filename: file('packages/ui/src/components/example.tsx'),
      languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
      errors: [{ messageId: 'comment' }],
    },
    {
      name: 'section dividers, TODOs and workaround links without a removal condition',
      code: [
        '// ---------------------------------------------------------------------------',
        '// TODO tighten when G5 is fixed',
        '// Workaround: https://github.com/payloadcms/payload/pull/18188',
        'export const a = 1;',
      ].join('\n'),
      output: 'export const a = 1;',
      filename: file('test/gateway/example.int.spec.ts'),
      errors: Array.from({ length: 3 }, () => ({ messageId: 'comment' })),
    },
    {
      name: 'eslint disables without a reason',
      code: [
        '// eslint-disable-next-line no-console',
        "console.log('x');",
        '/* eslint-disable no-console */',
      ].join('\n'),
      filename,
      errors: [{ messageId: 'reason' }, { messageId: 'reason' }],
    },
  ],
});
