// DO NOT MODIFY. Auto-generated by vitest.setup.ts from FROGBOT_DATABASE env var.

  import { mongooseAdapter } from '@frogbot/db-mongodb'

  export const databaseAdapter = mongooseAdapter({
    url: process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/frogbot-test',
  })
