/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    files: File;
    'admin-request-pages': AdminRequestPage;
    'admin-request-broken-pages': AdminRequestBrokenPage;
    'admin-request-assets': AdminRequestAsset;
    'frogbot-waitpoints': FrogBotWaitpoint;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    files: FilesSelect;
    'admin-request-pages': AdminRequestPagesSelect;
    'admin-request-broken-pages': AdminRequestBrokenPagesSelect;
    'admin-request-assets': AdminRequestAssetsSelect;
    'frogbot-waitpoints': FrogBotWaitpointsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'es')
    | ('en' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'frogbot-sweep-jobs': TaskFrogBotSweepJobs;
      'frogbot-cleanup-kv': TaskFrogBotCleanupKv;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  folder?: (number | null) | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-pages".
 */
export interface AdminRequestPage {
  id: number;
  title?: string | null;
  owner?: (number | null) | User;
  image?: (number | null) | File;
  color?: ('red' | 'green') | null;
  layout?:
    | {
        heading?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-broken-pages".
 */
export interface AdminRequestBrokenPage {
  id: number;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-assets".
 */
export interface AdminRequestAsset {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints".
 */
export interface FrogBotWaitpoint {
  id: number;
  jobId: string;
  holder?: (number | null) | null;
  name: string;
  token: string;
  kind: 'delay' | 'resumable';
  ready: boolean;
  status: 'pending' | 'resumed' | 'expired';
  expiresAt?: string | null;
  until?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dispatched: boolean;
  dispatchOwner?: string | null;
  dispatchLeaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  name?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  resetPasswordRequestedAt?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect {
  folder?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-pages_select".
 */
export interface AdminRequestPagesSelect {
  title?: boolean;
  owner?: boolean;
  image?: boolean;
  color?: boolean;
  layout?:
    | boolean
    | {
        hero?:
          | boolean
          | {
              heading?: boolean;
              id?: boolean;
              blockName?: boolean;
            };
      };
  body?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-broken-pages_select".
 */
export interface AdminRequestBrokenPagesSelect {
  title?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-request-assets_select".
 */
export interface AdminRequestAssetsSelect {
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints_select".
 */
export interface FrogBotWaitpointsSelect {
  jobId?: boolean;
  holder?: boolean;
  name?: boolean;
  token?: boolean;
  kind?: boolean;
  ready?: boolean;
  status?: boolean;
  expiresAt?: boolean;
  until?: boolean;
  data?: boolean;
  dispatched?: boolean;
  dispatchOwner?: boolean;
  dispatchLeaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotSweepJobs".
 */
export interface TaskFrogBotSweepJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogBotCleanupKv".
 */
export interface TaskFrogBotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {};
    models: never;
    roles: never;
  }
}
