import fs from 'fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

type DbAdapter = {
  envVar?: string
  host?: string
  label?: string
  port?: number
  profile?: 'postgres' | 'mongodb'
  source: string
}

const POSTGRES = {
  envVar: 'POSTGRES_URL',
  host: 'localhost',
  port: 5433,
  label: 'PostgreSQL',
  profile: 'postgres',
} as const

export const dbAdapters = {
  mongodb: {
    envVar: 'MONGODB_URI',
    host: 'localhost',
    port: 27018,
    label: 'MongoDB',
    profile: 'mongodb',
    source: `
  import { mongooseAdapter } from '@frogbot/db-mongodb'

  export const databaseAdapter = mongooseAdapter({
    ensureIndexes: true,
    url: process.env.MONGODB_URI || 'mongodb://localhost:27018/frogbot-test?directConnection=true&replicaSet=rs0',
  })`,
  },
  postgres: {
    ...POSTGRES,
    source: `
  import { postgresAdapter } from '@frogbot/db-postgres'

  export const databaseAdapter = postgresAdapter({
    pool: {
      connectionString: process.env.POSTGRES_URL || process.env.DATABASE_URL || 'postgres://frogbot:frogbot@localhost:5433/frogbot',
    },
  })`,
  },
  sqlite: {
    label: 'SQLite (file-based)',
    source: `
  import { sqliteAdapter } from '@frogbot/db-sqlite'

  export const databaseAdapter = sqliteAdapter({
    client: {
      url: process.env.SQLITE_URL || process.env.DATABASE_URL || 'file:./test-payload.db',
    },
  })`,
  },
} as const satisfies Record<string, DbAdapter>

export type DatabaseAdapterType = keyof typeof dbAdapters

/**
 * Write the chosen adapter's source to test/databaseAdapter.js.
 * Called from vitest.setup.ts before any test file imports it.
 */
export function generateDatabaseAdapter(dbAdapter: DatabaseAdapterType) {
  const adapter = dbAdapters[dbAdapter]
  if (!adapter) {
    throw new Error(`[test] Unknown database adapter: ${dbAdapter}`)
  }

  const testRoot = path.resolve(dirname, '../../..')
  fs.writeFileSync(
    path.resolve(testRoot, 'databaseAdapter.js'),
    `// DO NOT MODIFY. Auto-generated by vitest.setup.ts from FROGBOT_DATABASE env var.\n${adapter.source}\n`,
  )

  console.log(`[test] Wrote ${dbAdapter} adapter to test/databaseAdapter.js`)
}

export function getCurrentDatabaseAdapter(): DatabaseAdapterType {
  const dbAdapter = process.env.FROGBOT_DATABASE as DatabaseAdapterType | undefined
  if (dbAdapter && dbAdapter in dbAdapters) {
    return dbAdapter
  }
  return 'mongodb'
}
