/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by FrogBot.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source FrogBot config,
 * and re-run `frogbot generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    chats: Chat;
    messages: Message;
    'frogbot-chat-assets': FrogbotChatAsset;
    'usage-logs': UsageLog;
    'frogbot-trigger-subscriptions': FrogbotTriggerSubscription;
    'frogbot-waitpoints': FrogbotWaitpoint;
    files: File;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    chats: ChatsSelect;
    messages: MessagesSelect;
    'frogbot-chat-assets': FrogbotChatAssetsSelect;
    'usage-logs': UsageLogsSelect;
    'frogbot-trigger-subscriptions': FrogbotTriggerSubscriptionsSelect;
    'frogbot-waitpoints': FrogbotWaitpointsSelect;
    files: FilesSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'frogbot-reset-ai-budgets': TaskFrogbotResetAiBudgets;
      'frogbot-sweep-jobs': TaskFrogbotSweepJobs;
      'frogbot-cleanup-kv': TaskFrogbotCleanupKv;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  modelAccess?: ('all' | 'selected') | null;
  models?: 'test/gpt-4.1-mini'[] | null;
  monthlyBudget?: number | null;
  spendThisPeriodUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats".
 */
export interface Chat {
  id: number;
  sharedWith?: (number | User)[] | null;
  title?: string | null;
  user?: (number | null) | User;
  agent?: string | null;
  channel?: string | null;
  externalId?: string | null;
  channelKey?: string | null;
  lastMessageAt?: string | null;
  todos?: import('frogbot/tools').TodoItem[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  chat: number | Chat;
  role: 'user' | 'assistant' | 'system';
  parts: import('frogbot').UIMessage['parts'];
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usage?: {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
    reasoningTokens?: number | null;
    cachedInputTokens?: number | null;
    model?: string | null;
    provider?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-assets".
 */
export interface FrogbotChatAsset {
  id: number;
  owner?: (number | null) | User;
  chat?: (number | null) | Chat;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs".
 */
export interface UsageLog {
  id: number;
  user?: (number | null) | User;
  chat?: (number | null) | Chat;
  requestId: string;
  runId?: string | null;
  model: string;
  operation:
    | 'chat.completions'
    | 'messages'
    | 'responses'
    | 'embeddings'
    | 'images'
    | 'speech'
    | 'transcriptions'
    | 'videos'
    | 'rerank';
  inputTokens: number;
  outputTokens: number;
  cachedInputTokens?: number | null;
  cacheWriteTokens?: number | null;
  reasoningTokens?: number | null;
  totalTokens: number;
  costUSD: number;
  finishReason?: string | null;
  requestedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-trigger-subscriptions".
 */
export interface FrogbotTriggerSubscription {
  id: number;
  agent: string;
  piece: string;
  instance: string;
  trigger: string;
  inputHash: string;
  input:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  webhookUrl?: string | null;
  status: 'active' | 'error';
  cleanupPending?: boolean | null;
  enablePending?: boolean | null;
  enableAttempt?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints".
 */
export interface FrogbotWaitpoint {
  id: number;
  jobId: string;
  name: string;
  token: string;
  kind: 'delay' | 'resumable';
  ready: boolean;
  status: 'pending' | 'resumed' | 'expired';
  expiresAt?: string | null;
  until?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dispatched: boolean;
  dispatchOwner?: string | null;
  dispatchLeaseUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  folder?: (number | null) | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  name?: boolean;
  modelAccess?: boolean;
  models?: boolean;
  monthlyBudget?: boolean;
  spendThisPeriodUSD?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  resetPasswordRequestedAt?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats_select".
 */
export interface ChatsSelect {
  sharedWith?: boolean;
  title?: boolean;
  user?: boolean;
  agent?: boolean;
  channel?: boolean;
  externalId?: boolean;
  channelKey?: boolean;
  lastMessageAt?: boolean;
  todos?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect {
  id?: boolean;
  chat?: boolean;
  role?: boolean;
  parts?: boolean;
  metadata?: boolean;
  usage?:
    | boolean
    | {
        inputTokens?: boolean;
        outputTokens?: boolean;
        totalTokens?: boolean;
        reasoningTokens?: boolean;
        cachedInputTokens?: boolean;
        model?: boolean;
        provider?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-chat-assets_select".
 */
export interface FrogbotChatAssetsSelect {
  owner?: boolean;
  chat?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-logs_select".
 */
export interface UsageLogsSelect {
  user?: boolean;
  chat?: boolean;
  requestId?: boolean;
  runId?: boolean;
  model?: boolean;
  operation?: boolean;
  inputTokens?: boolean;
  outputTokens?: boolean;
  cachedInputTokens?: boolean;
  cacheWriteTokens?: boolean;
  reasoningTokens?: boolean;
  totalTokens?: boolean;
  costUSD?: boolean;
  finishReason?: boolean;
  requestedAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-trigger-subscriptions_select".
 */
export interface FrogbotTriggerSubscriptionsSelect {
  agent?: boolean;
  piece?: boolean;
  instance?: boolean;
  trigger?: boolean;
  inputHash?: boolean;
  input?: boolean;
  state?: boolean;
  webhookUrl?: boolean;
  status?: boolean;
  cleanupPending?: boolean;
  enablePending?: boolean;
  enableAttempt?: boolean;
  expiresAt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frogbot-waitpoints_select".
 */
export interface FrogbotWaitpointsSelect {
  jobId?: boolean;
  name?: boolean;
  token?: boolean;
  kind?: boolean;
  ready?: boolean;
  status?: boolean;
  expiresAt?: boolean;
  until?: boolean;
  data?: boolean;
  snapshot?: boolean;
  dispatched?: boolean;
  dispatchOwner?: boolean;
  dispatchLeaseUntil?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect {
  folder?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  deletedAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogbot-reset-ai-budgets".
 */
export interface TaskFrogbotResetAiBudgets {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogbot-sweep-jobs".
 */
export interface TaskFrogbotSweepJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFrogbot-cleanup-kv".
 */
export interface TaskFrogbotCleanupKv {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'frogbot' {
  export interface GeneratedTypes extends Config {
    agents: {
      support: unknown;
    };
    models: 'test/gpt-4.1-mini';
    roles: never;
  }
}
